-- Part 1: University-level data for University of Southampton
UPDATE public.universities SET
  website_url = 'https://www.southampton.ac.uk',
  tuition_usd = 29700,
  overall_acceptance_rate = '15%',
  test_policy = 'Not applicable',
  deadline_calendar = 'UCAS deadline: January 29 (18:00 GMT) for September entry. Equal consideration given to all applications received by the deadline. No early action or early decision. Deferred entry (gap year) applications accepted. International qualifications assessed on equivalent basis.',
  financial_aid = 'Southampton Undergraduate Scholarship for International Students (merit-based, up to £5,000/year); Vice-Chancellor Scholarship (up to £10,000/year for high-achieving international students); Hampshire County Council Scholarship; subject-specific bursaries in Engineering and Science; UK Home students eligible for government tuition fee loans and means-tested maintenance grants. Scholarships applied for via the university scholarship portal after receiving an offer.'
WHERE name = 'University of Southampton';

-- Part 2: Top 10 majors for University of Southampton
INSERT INTO public.majors (university_id, major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
SELECT u.id, v.major_name, v.acceptance_rate, v.supplemental_requirements, v.subject_ranking, v.ielts_min, v.toefl_min, v.sat_min, v.act_min, v.gpa_min, v.a_level_grades, v.ib_min, v.atar_min, v.duolingo_min, v.pte_min
FROM public.universities u
CROSS JOIN (VALUES
  ('BEng Electronic Engineering',       '18%', 'A-Level Mathematics and Physics required; personal statement should demonstrate interest in electronics and problem-solving; strong GCSE profile expected including Mathematics and a science',                                                                                                             45,  6.5::numeric, 90, NULL::integer, NULL::integer, 3.5::numeric, 'AAB', 33, NULL::numeric, 115, 61),
  ('MEng Electronic Engineering',       '14%', 'A-Level Mathematics and Physics required; Further Mathematics desirable; personal statement should demonstrate strong analytical interest and motivation for the integrated masters; strong GCSE profile expected',                                                                                    45,  6.5::numeric, 90, NULL::integer, NULL::integer, 3.5::numeric, 'AAA', 34, NULL::numeric, 115, 61),
  ('BEng Civil Engineering',            '20%', 'A-Level Mathematics required; Physics or a second science/technical subject desirable; personal statement should reflect interest in infrastructure and the built environment; strong GCSE profile expected',                                                                                          95,  6.5::numeric, 90, NULL::integer, NULL::integer, 3.5::numeric, 'ABB', 32, NULL::numeric, 110, 59),
  ('BSc Computer Science',              '16%', 'A-Level Mathematics required; Computing or Further Mathematics desirable but not essential; personal statement should demonstrate programming experience and genuine interest in computing; strong GCSE profile expected',                                                                              90,  6.5::numeric, 90, NULL::integer, NULL::integer, 3.5::numeric, 'AAB', 33, NULL::numeric, 110, 59),
  ('BEng Mechanical Engineering',       '19%', 'A-Level Mathematics and Physics required; personal statement should show enthusiasm for engineering design and mechanics; strong GCSE profile expected including Mathematics and Physics',                                                                                                              120, 6.5::numeric, 90, NULL::integer, NULL::integer, 3.5::numeric, 'ABB', 32, NULL::numeric, 110, 59),
  ('BSc Physics',                       '22%', 'A-Level Mathematics and Physics required; Further Mathematics desirable; personal statement should demonstrate genuine curiosity for physical sciences and any relevant activities such as astronomy clubs or extended projects',                                                                        85,  6.5::numeric, 90, NULL::integer, NULL::integer, 3.5::numeric, 'AAB', 33, NULL::numeric, 110, 59),
  ('BSc Oceanography',                  '25%', 'A-Level Mathematics and one science (Biology, Chemistry, or Physics) required; personal statement should reflect interest in marine and environmental sciences; Southampton is a world-leading centre for oceanography',                                                                                 8,   6.5::numeric, 90, NULL::integer, NULL::integer, 3.3::numeric, 'ABB', 32, NULL::numeric, 110, 59),
  ('LLB Law',                           '12%', 'No specific A-Level subjects required; essay-based subjects such as History, English, or Politics highly valued; LNAT (Law National Admissions Test) required; personal statement must demonstrate analytical and critical thinking skills and genuine interest in law',                                 90,  6.5::numeric, 90, NULL::integer, NULL::integer, 3.5::numeric, 'AAB', 33, NULL::numeric, 110, 59),
  ('BSc Biomedical Sciences',           '17%', 'A-Level Biology and Chemistry required; third science or Mathematics desirable; personal statement should demonstrate interest in the scientific basis of medicine and healthcare; strong GCSE profile expected',                                                                                      130, 6.5::numeric, 90, NULL::integer, NULL::integer, 3.5::numeric, 'ABB', 32, NULL::numeric, 110, 59),
  ('BSc Economics',                     '20%', 'A-Level Mathematics required at Grade A; personal statement should demonstrate analytical reasoning and genuine interest in economics; Further Mathematics desirable; strong GCSE profile expected',                                                                                                    130, 6.5::numeric, 90, NULL::integer, NULL::integer, 3.5::numeric, 'AAB', 33, NULL::numeric, 110, 59)
) AS v(major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
WHERE u.name = 'University of Southampton';
