INSERT INTO public.majors (university_id, major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
SELECT u.id, v.major_name, v.acceptance_rate, v.supplemental_requirements, v.subject_ranking, v.ielts_min, v.toefl_min, v.sat_min, v.act_min, v.gpa_min, v.a_level_grades, v.ib_min, v.atar_min, v.duolingo_min, v.pte_min
FROM public.universities u
CROSS JOIN (VALUES
  ('Engineering (Honours)', 70.0, 'Prerequisites: Year 12 Mathematics and Physics or Chemistry; 4-year honours-integrated program; apply via UAC', NULL::INTEGER, 6.0, 79, NULL::INTEGER, NULL::INTEGER, NULL::NUMERIC, 'BCC', 28, 70.0, 100, 58),
  ('Nursing', 75.0, 'Prerequisites: Year 12 English and one science subject recommended; IELTS 7.0 with no band below 7.0 required for registration; clinical placements required', NULL::INTEGER, 7.0, 94, NULL::INTEGER, NULL::INTEGER, NULL::NUMERIC, 'BBB', 30, 70.0, 110, 65),
  ('Medicine (Doctor of Medicine - graduate entry)', 5.0, 'Undergraduate pathway via Bachelor of Biomedical Science; UCAT ANZ required for direct entry pathway; ATAR 99+ for direct entry; highly competitive', NULL::INTEGER, 7.0, 94, NULL::INTEGER, NULL::INTEGER, NULL::NUMERIC, 'A*AA', 42, 99.0, 120, 65),
  ('Business', 80.0, 'Prerequisites: Year 12 Mathematics Standard 2 or equivalent; broad program covering management, marketing, accounting, and HR', NULL::INTEGER, 6.0, 79, NULL::INTEGER, NULL::INTEGER, NULL::NUMERIC, 'BCC', 28, 65.0, 100, 58),
  ('Computer Science', 75.0, 'Prerequisites: Year 12 Mathematics Advanced or equivalent recommended; assumed knowledge of HSC Software Design and Development advantageous', NULL::INTEGER, 6.0, 79, NULL::INTEGER, NULL::INTEGER, NULL::NUMERIC, 'BCC', 28, 70.0, 100, 58),
  ('Psychology', 78.0, 'Prerequisites: Year 12 English Standard or Advanced; fourth-year honours stream requires separate application; accredited by APS', NULL::INTEGER, 6.0, 79, NULL::INTEGER, NULL::INTEGER, NULL::NUMERIC, 'BCC', 28, 68.0, 100, 58),
  ('Education (Primary)', 80.0, 'Prerequisites: Year 12 English Band 4 minimum; literacy and numeracy test (LANTITE) required prior to graduation; apply via UAC', NULL::INTEGER, 7.0, 94, NULL::INTEGER, NULL::INTEGER, NULL::NUMERIC, 'BCC', 28, 65.0, 110, 58),
  ('Biomedical Science', 75.0, 'Prerequisites: Year 12 Chemistry and Biology or Mathematics recommended; pathway to postgraduate medicine and health professions', NULL::INTEGER, 6.0, 79, NULL::INTEGER, NULL::INTEGER, NULL::NUMERIC, 'BCC', 28, 70.0, 100, 58),
  ('Law (combined degrees only)', 25.0, 'Offered as combined degree (e.g. BA/LLB, BCom/LLB); no standalone LLB; apply via UAC; ATAR 80 for combined program', NULL::INTEGER, 6.5, 85, NULL::INTEGER, NULL::INTEGER, NULL::NUMERIC, 'ABB', 32, 80.0, 110, 58),
  ('Architecture', 72.0, 'Prerequisites: Year 12 Mathematics recommended; 3-year Bachelor of Design (Architecture pathway) leads to Master of Architecture; no portfolio required for UG entry', NULL::INTEGER, 6.0, 79, NULL::INTEGER, NULL::INTEGER, NULL::NUMERIC, 'BCC', 28, 68.0, 100, 58)
) AS v(major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
WHERE u.name = 'The University of Newcastle';
