-- Part 1: University-level data for King's College London (KCL)
UPDATE public.universities SET
  website_url = 'https://www.kcl.ac.uk',
  tuition_usd = 38430,
  overall_acceptance_rate = '14%',
  test_policy = 'Not applicable',
  deadline_calendar = 'UCAS deadline: 15 October 2025 (18:00 UK time) for Medicine and Dentistry; 29 January 2026 (18:00 UK time) equal consideration deadline for all other undergraduate courses (Law, Arts, Engineering, Sciences, Business, etc.). 30 June 2026 final deadline for late applications. All applications via UCAS. Deferred entry accepted for most programmes.',
  financial_aid = 'King''s International Scholarship: merit-based awards for high-achieving international undergraduate students (partial tuition fee waivers, value varies by programme). King''s Access Support (KAAS Scheme): reduced-rent accommodation for students from households with income below £42,875/year. Hardship Fund: emergency financial assistance for students in unexpected financial difficulty. External scholarships supported: Chevening Scholarships (UK government, full funding for postgraduate), Commonwealth Scholarships, and various country-specific awards. UK home students eligible for government Tuition Fee Loan (up to £9,790/year) and means-tested Maintenance Loan via Student Finance England.'
WHERE name = 'King''s College London (KCL)';

-- Part 2: Delete existing majors and re-insert top 10 for King's College London (KCL)
DELETE FROM public.majors WHERE university_id = (SELECT id FROM public.universities WHERE name = 'King''s College London (KCL)');

INSERT INTO public.majors (university_id, major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
SELECT u.id, v.major_name, v.acceptance_rate, v.supplemental_requirements, v.subject_ranking, v.ielts_min, v.toefl_min, v.sat_min, v.act_min, v.gpa_min, v.a_level_grades, v.ib_min, v.atar_min, v.duolingo_min, v.pte_min
FROM public.universities u
CROSS JOIN (VALUES
  ('MBBS Medicine', '6%', 'UCAT (University Clinical Aptitude Test) mandatory; interview (MMI format) required; A-Level Chemistry required plus Biology or Mathematics; personal statement must demonstrate clinical work experience and genuine motivation for medicine; GCSEs assessed (typically 7-9/A-A* in Sciences and English)', 'QS #7 World (Medicine)', 7.0, 100, NULL, NULL, NULL, 'A*AA', 38, NULL, NULL, 68),
  ('LLB Law', '12%', 'LNAT (National Admissions Test for Law) required (score typically 27+ competitive); no fixed A-Level subject requirements but essay-based subjects (History, English, Politics) highly valued; personal statement must demonstrate analytical ability and genuine interest in law; strong GCSEs expected (mostly 7-9/A-A*)', 'QS #16 World (Law)', 7.0, 100, NULL, NULL, NULL, 'AAA', 37, NULL, NULL, 68),
  ('BSc Business Management', '19%', 'No specific A-Level subject requirements; A-Level Mathematics advantageous; personal statement must demonstrate commercial awareness, leadership potential and genuine interest in business; strong GCSEs expected; interviews not standard but contextual admissions considered', 'QS Top 100 World (Business & Management Studies)', 6.5, 92, NULL, NULL, NULL, 'AAB', 35, NULL, NULL, 65),
  ('BSc International Relations', '18%', 'No specific A-Level subject requirements; essay-based subjects (History, Politics, Economics, Geography) highly valued; personal statement must demonstrate engagement with global affairs and current international issues; strong GCSEs expected', 'QS #17 World (Politics & International Studies)', 6.5, 92, NULL, NULL, NULL, 'AAB', 35, NULL, NULL, 65),
  ('BSc Economics', '15%', 'A-Level Mathematics required (grade A minimum); Further Mathematics desirable; personal statement should demonstrate quantitative aptitude and genuine interest in economic theory and its application; strong GCSEs expected (7-9 in Mathematics)', 'QS Top 50 World (Economics & Econometrics)', 7.0, 100, NULL, NULL, NULL, 'AAA', 36, NULL, NULL, 68),
  ('BSc Biomedical Science', '20%', 'A-Level Biology and Chemistry both required (grade A minimum); personal statement must demonstrate understanding of biomedical research and career intentions; laboratory work experience beneficial; strong GCSEs expected in Sciences', 'QS Top 100 World (Life Sciences & Medicine)', 6.5, 92, NULL, NULL, NULL, 'AAA', 36, NULL, NULL, 65),
  ('BSc Computer Science', '25%', 'A-Level Mathematics required (grade A minimum); Further Mathematics or Physics advantageous; personal statement should demonstrate programming experience, problem-solving skills and passion for computing; no mandatory admissions test', 'QS Top 150 World (Computer Science & Information Systems)', 6.5, 92, NULL, NULL, NULL, 'AAB', 35, NULL, NULL, 65),
  ('BSc Psychology', '14%', 'No specific A-Level subject requirements; Biology or Mathematics advantageous; personal statement must demonstrate understanding of psychology as a science, critical thinking skills and awareness of ethical issues in research; strong GCSEs expected', 'QS #15 World (Psychology)', 7.0, 100, NULL, NULL, NULL, 'AAA', 36, NULL, NULL, 68),
  ('BNurs Nursing (Adult)', '30%', 'Relevant healthcare/caring work experience strongly recommended; personal statement must demonstrate compassion, communication skills and commitment to nursing; DBS (Disclosure and Barring Service) check required; occupational health check required; no specific A-Level subject requirement but Biology or Health & Social Care valued', 'QS Top 50 World (Nursing)', 7.0, 100, NULL, NULL, NULL, 'ABB', 34, NULL, NULL, 65),
  ('MPharm Pharmacy', '22%', 'A-Level Chemistry required (grade A minimum); Biology or Mathematics as second science advantageous; GCSE Mathematics grade 6/B minimum; personal statement should demonstrate understanding of pharmacy practice and patient care; interview may be required for borderline applicants', 'QS Top 50 World (Pharmacy & Pharmacology)', 6.5, 92, NULL, NULL, NULL, 'AAB', 35, NULL, NULL, 65)
) AS v(major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
WHERE u.name = 'King''s College London (KCL)';
