INSERT INTO public.majors (university_id, major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
SELECT u.id, v.major_name, v.acceptance_rate, v.supplemental_requirements, v.subject_ranking, v.ielts_min, v.toefl_min, v.sat_min, v.act_min, v.gpa_min, v.a_level_grades, v.ib_min, v.atar_min, v.duolingo_min, v.pte_min
FROM public.universities u
CROSS JOIN (VALUES
  ('Commerce',              NULL::TEXT, 'Assumed knowledge: HSC Mathematics Advanced or equivalent; ATAR-based selection rank 96',                                                            50,  7.0, 96,  NULL::INTEGER, NULL::INTEGER, NULL::NUMERIC, 'AAB',  38, 96.0,  115, 72),
  ('Law',                   NULL,       'Combined degree only (e.g. B Arts/B Laws, B Commerce/B Laws); no standalone undergraduate LLB; ATAR 99.5',                                          20,  7.5, 105, NULL,          NULL,          NULL,          'A*AA', 38, 99.5,  120, 78),
  ('Engineering',           NULL,       'Assumed knowledge: HSC Mathematics Extension 1 and Physics or equivalent; honours integrated 4-year program; ATAR 90',                              55,  6.5, 85,  NULL,          NULL,          NULL,          'ABB',  33, 90.0,  110, 64),
  ('Arts',                  NULL,       'Standard university application; broad elective choice across humanities and social sciences; ATAR 80',                                              30,  6.5, 85,  NULL,          NULL,          NULL,          'BBB',  29, 80.0,  110, 64),
  ('Science',               NULL,       'Assumed knowledge: varies by major; typically HSC Mathematics Advanced plus one science subject; ATAR 80',                                          50,  6.5, 85,  NULL,          NULL,          NULL,          'BBB',  29, 80.0,  110, 64),
  ('Economics',             NULL,       'Assumed knowledge: HSC Mathematics Advanced or equivalent; ATAR 91',                                                                                28,  7.0, 96,  NULL,          NULL,          NULL,          'ABB',  33, 91.0,  115, 72),
  ('Architecture and Environments', NULL, 'Standard university application; no portfolio required for entry; ATAR 85; 3-year Bachelor leads to postgraduate architecture',                   28,  7.0, 96,  NULL,          NULL,          NULL,          'BBB',  29, 85.0,  115, 72),
  ('Nursing',               NULL,       'Must meet ANMAC English requirements; clinical placements required; IELTS 7.0 with 7.0 in each band; ATAR 84',                                     14,  7.0, 96,  NULL,          NULL,          NULL,          'BBB',  30, 84.0,  115, 72),
  ('Psychology',            NULL,       'Assumed knowledge: HSC Mathematics Standard 2 or equivalent; fourth-year honours stream requires separate application; ATAR 85',                   25,  6.5, 85,  NULL,          NULL,          NULL,          'ABB',  31, 85.0,  110, 64),
  ('Computer Science (Advanced Computing)', NULL, 'Prerequisite: HSC Mathematics Extension 1 or equivalent; ATAR 90; mathematics proficiency test may be required',                         42,  6.5, 85,  NULL,          NULL,          NULL,          'ABB',  33, 90.0,  110, 64)
) AS v(major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
WHERE u.name = 'The University of Sydney';
