-- Part 1: University-level data for McGill University
UPDATE public.universities SET
  website_url = 'https://www.mcgill.ca',
  tuition_usd = 35000,
  overall_acceptance_rate = '46%',
  test_policy = 'Test-optional',
  deadline_calendar = 'Most undergraduate programs: January 15 deadline for fall entry. Some competitive programs (Medicine, Law, Dentistry) have earlier deadlines. Applications submitted via the McGill online application portal. Deferred entry available for most programs. International applicants should apply by January 15 to ensure full consideration.',
  financial_aid = 'Merit-based entrance scholarships awarded automatically at admission (no separate application required) for students with exceptional academic records; Alma Mater Fund scholarships; In-course awards for continuing students; McGill Work-Study Program for eligible students; International students are eligible for entrance scholarships but most need-based aid is restricted to Quebec residents; guaranteed tuition model for admitted international undergraduates locks in tuition rate for the duration of the program.'
WHERE name = 'McGill University';

-- Part 2: Replace majors for McGill University
DELETE FROM public.majors WHERE university_id = (SELECT id FROM public.universities WHERE name = 'McGill University');

INSERT INTO public.majors (university_id, major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
SELECT u.id, v.major_name, v.acceptance_rate, v.supplemental_requirements, v.subject_ranking, v.ielts_min, v.toefl_min, v.sat_min, v.act_min, v.gpa_min, v.a_level_grades, v.ib_min, v.atar_min, v.duolingo_min, v.pte_min
FROM public.universities u
CROSS JOIN (VALUES
  ('Computer Science',           0.25, 'Mathematics prerequisite required (Pre-Calculus or equivalent); no supplemental essay but strong academic record in STEM expected; SAT/ACT optional but competitive applicants typically score 1400+ SAT or 32+ ACT.',                    'QS #33 (Computer Science & Information Systems)', 6.5, 90, NULL::INTEGER, NULL::INTEGER, 3.8, 'A*AA including Mathematics', 38, NULL::NUMERIC, 125, 65),
  ('Mechanical Engineering',     0.28, 'Math, Chemistry, and Physics prerequisites required; no supplemental essay; highly competitive applicants typically have 90%+ average; SAT/ACT optional.',                                                                              'QS #51-100 (Engineering - Mechanical)',           6.5, 90, NULL,           NULL,           3.7, 'A*A*A including Mathematics and Physics', 37, NULL, 125, 65),
  ('Commerce (Desautels)',        0.22, 'Supplemental short-answer essays required via Desautels Faculty of Management application; Mathematics prerequisite; strong extracurricular profile expected; SAT/ACT optional but 1350+ SAT considered competitive.',                'QS #51-100 (Business & Management Studies)',      6.5, 100, NULL,          NULL,           3.7, 'AAA including Mathematics',              37, NULL, 130, 65),
  ('Biology',                    0.42, 'Two of Biology, Chemistry, or Physics required as prerequisites; no supplemental essay; well-rounded academic profile expected.',                                                                                                      'QS #44 (Biological Sciences)',                    6.5, 90, NULL,           NULL,           3.5, 'AAA including one Science',              34, NULL, 125, 65),
  ('Psychology',                 0.50, 'No supplemental essay; admitted through Faculty of Arts or Science depending on specialization; strong grades in relevant coursework expected.',                                                                                       'QS #27 (Psychology)',                             6.5, 90, NULL,           NULL,           3.5, 'AAA',                                   33, NULL, 125, 65),
  ('Political Science',          0.52, 'No supplemental essay; admitted through Faculty of Arts; broad social sciences background valued.',                                                                                                                                    'QS #51-100 (Politics & International Studies)',   6.5, 90, NULL,           NULL,           3.5, 'AAA',                                   33, NULL, 125, 65),
  ('Economics',                  0.45, 'Mathematics prerequisite recommended; no supplemental essay; admitted through Faculty of Arts; quantitative aptitude expected.',                                                                                                       'QS #51-100 (Economics & Econometrics)',           6.5, 90, NULL,           NULL,           3.5, 'AAA including Mathematics',              33, NULL, 125, 65),
  ('Nursing',                    0.45, 'Resume, personal statement, and two letters of reference required; Biology and Chemistry prerequisites; competitive entry with limited seats.',                                                                                         NULL,                                              6.5, 90, NULL,           NULL,           3.5, 'AAA including Biology and Chemistry',   33, NULL, 125, 65),
  ('Medicine and Surgery (MDCM)', 0.15, 'Four-year professional degree; prerequisites include 60 university credits covering Biology, Chemistry, Biochemistry, and Statistics; CASPer test required; MMI (Multiple Mini Interview) required; highly competitive.',           'QS #37 (Medicine)',                               7.0, 100, NULL,          NULL,           3.8, 'A*A*AA',                                38, NULL, 130, 65),
  ('Music',                      0.38, 'Audition required (instruments/voice); portfolio of compositions for composition applicants; theory and ear-training assessment; academic prerequisites apply; admission based jointly on academic record and audition performance.',  'QS Top 50 (Performing Arts)',                     6.5, 79,  NULL,          NULL,           3.3, 'ABB',                                   28, NULL, 125, 65)
) AS v(major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
WHERE u.name = 'McGill University';
