-- Part 1: University-level data for Leiden University
UPDATE public.universities SET
  website_url = 'https://www.universiteitleiden.nl/en/education/study-programmes/bachelor',
  tuition_usd = 15587,
  overall_acceptance_rate = '~63%',
  test_policy = 'Not applicable',
  deadline_calendar = 'Non-EEA students requiring visa/residence permit: 1 May 2025 (bachelor programs); Early Bird Non-EEA: 1 December 2024; Numerus fixus programs (Psychology, Political Science: IR&O): 15 January 2025; Regular deadline: 15 March 2025. Application fee: EUR 100 (non-refundable, covers up to 3 programs). Application via Studielink (national portal) then Leiden uSis portal.',
  financial_aid = 'NL Scholarship (Holland Scholarship): EUR 5,000 one-time award for non-EEA students enrolling in English-taught bachelor programs starting September 2025 (eligibility via studyinnl.org). Leiden Excellence Scholarship (LExS): partial to full tuition fee award for outstanding non-EEA master candidates. Huygens Scholarship Programme (Dutch government): covers tuition + living costs for exceptional non-EEA students. Leiden University Fund (LUF) scholarships: various merit and need-based awards. Low statutory tuition for EEA nationals: EUR 2,694/yr (2026-2027). Non-EEA institutional tuition: EUR 14,300/yr for most faculties; EUR 18,700/yr for Biomedical Sciences/Medicine; EUR 17,570/yr for LUC The Hague. Blocked account (~EUR 12,000-13,000/yr) required for non-EEA student visa application.'
WHERE name = 'Leiden University';

-- Part 2: Top 10 English-taught bachelor majors for Leiden University
INSERT INTO public.majors (university_id, major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
SELECT u.id, v.major_name, v.acceptance_rate, v.supplemental_requirements, v.subject_ranking, v.ielts_min, v.toefl_min, v.sat_min, v.act_min, v.gpa_min, v.a_level_grades, v.ib_min, v.atar_min, v.duolingo_min, v.pte_min
FROM public.universities u
CROSS JOIN (VALUES
  ('International Studies (BA)', NULL, 'English-taught; interdisciplinary programme combining culture, history, politics and economics with a regional focus area (Africa, East Asia, Europe, Latin America, Middle East, North America, Russia & Eurasia, South/Southeast Asia); proficiency in a regional language required alongside English; diploma equivalent to Dutch VWO required; IELTS academic with minimum 6.5 overall and minimum 6.0 per component; application via Studielink + uSis; non-EEA deadline 1 May; Leiden ranks QS Top 200 World (Arts & Humanities)', NULL, 6.5, 90, NULL, NULL, NULL, 'BBB', 30, NULL, NULL, 58),
  ('Psychology (BSc)', '25%', 'Numerus fixus programme with limited places (~350/year); highly competitive selection via weighted lottery (decentrale selectie); English-taught; requires pre-university diploma equivalent to Dutch VWO; strong background in sciences/social sciences recommended; selection based on extracurricular activities, motivation, and grades; IELTS 6.5 overall minimum 6.0 per component; application deadline 15 January (numerus fixus); Leiden ranks QS #51-100 World (Psychology)', NULL, 6.5, 90, NULL, NULL, NULL, 'BBB', 30, NULL, NULL, 58),
  ('Political Science: International Relations and Organisations (BSc)', '30%', 'Numerus fixus programme with ~350 places; selection procedure based on grades, motivation letter, extracurricular activities; English-taught; strong social sciences background preferred; diploma equivalent to Dutch VWO required; IELTS 6.5 overall minimum 6.0 per component; application deadline 15 January (numerus fixus); programme based at Leiden campus; Leiden ranks QS #51-100 World (Politics & International Studies)', NULL, 6.5, 90, NULL, NULL, NULL, 'BBB', 30, NULL, NULL, 58),
  ('Liberal Arts and Sciences: Global Challenges (BA/BSc)', NULL, 'Offered at Leiden University College (LUC) The Hague; English-taught; residential programme (on-campus living required first year); interdisciplinary with tracks in Humanities & Social Sciences, and Science; additional institutional tuition fee EUR 2,990/yr on top of standard tuition; IELTS 7.0 overall minimum 6.5 per component; application deadline 15 January; selection includes motivation letter, academic references, and writing sample; application fee EUR 50 (separate from main fee); Leiden ranks QS Top 250 World (Arts & Humanities; Social Sciences)', NULL, 7.0, 100, NULL, NULL, NULL, 'ABB', 32, NULL, NULL, 65),
  ('English Language and Culture (BA)', NULL, 'English-taught; covers linguistics, literature, and cultural analysis in the English-speaking world; strong interest in literary analysis and language study required; diploma equivalent to Dutch VWO; IELTS 6.5 overall minimum 6.0 per component; non-EEA deadline 1 May; programme based at Leiden campus; regular deadline 15 March; Leiden ranks QS Top 150 World (Linguistics)', NULL, 6.5, 90, NULL, NULL, NULL, 'BBB', 29, NULL, NULL, 58),
  ('History (BA)', NULL, 'English-taught track available; interdisciplinary approach covering world, European, and regional history; strong essay writing skills required; diploma equivalent to Dutch VWO; IELTS 6.5 overall minimum 6.0 per component; regular deadline 15 March; non-EEA deadline 1 May; no specific A-level subject required but humanities background valued; Leiden ranks QS Top 100 World (History)', NULL, 6.5, 90, NULL, NULL, NULL, 'BBB', 29, NULL, NULL, 58),
  ('Philosophy (BA)', NULL, 'English-taught track available; covers analytic and continental philosophy, ethics, logic, and history of philosophy; strong argumentation and writing skills required; diploma equivalent to Dutch VWO; IELTS 6.5 overall minimum 6.0 per component; regular deadline 15 March; non-EEA deadline 1 May; humanities background valued; Leiden ranks QS Top 100 World (Philosophy)', NULL, 6.5, 90, NULL, NULL, NULL, 'BBB', 29, NULL, NULL, 58),
  ('Film and Literature Studies (BA)', NULL, 'English-taught; comparative approach to world cinema and literature; covers film theory, literary analysis, and cultural studies; diploma equivalent to Dutch VWO; strong written English required; IELTS 6.5 overall minimum 6.0 per component; regular deadline 15 March; non-EEA deadline 1 May; portfolio or writing sample may be requested; Leiden ranks QS Top 200 World (Arts & Humanities)', NULL, 6.5, 90, NULL, NULL, NULL, 'BBB', 29, NULL, NULL, 58),
  ('Governance, Economics and Development (BSc)', NULL, 'English-taught; offered at Faculty of Governance and Global Affairs (The Hague campus); interdisciplinary programme combining economics, public administration, and development studies; mathematics background recommended; diploma equivalent to Dutch VWO; IELTS 6.5 overall minimum 6.0 per component; regular deadline 15 March; non-EEA deadline 1 May; Leiden ranks QS Top 150 World (Politics & International Studies)', NULL, 6.5, 90, NULL, NULL, NULL, 'BBB', 30, NULL, NULL, 58),
  ('Life Science and Technology (BSc)', NULL, 'English-taught joint degree between Leiden University and Delft University of Technology; covers molecular biology, chemistry, and biotechnology with engineering applications; strong sciences background required (Biology, Chemistry, Mathematics at A-level equivalent); diploma equivalent to Dutch VWO; IELTS 6.5 overall minimum 6.0 per component; regular deadline 15 March; non-EEA deadline 1 May; physics or mathematics desirable; Leiden ranks QS Top 100 World (Biological Sciences)', NULL, 6.5, 90, NULL, NULL, NULL, 'ABB', 32, NULL, NULL, 58)
) AS v(major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
WHERE u.name = 'Leiden University';
