-- Part 1: University-level data for Universidad de Buenos Aires
UPDATE public.universities SET
  website_url = 'https://www.uba.ar/',
  tuition_usd = 0,
  overall_acceptance_rate = 'Open admission (unrestricted entry via CBC)',
  test_policy = 'Not applicable',
  deadline_calendar = 'Main intake: March (academic year start). CBC enrollment opens November-February for March start; some faculties also allow August intake. International students apply through Secretaría de Relaciones Internacionales. Exchange student deadlines vary by faculty (e.g., Law: October-November for March-July semester). No standardized test deadlines.',
  financial_aid = 'All undergraduate programs are tuition-free for all students regardless of nationality (since 1949). Beca Bicentenario for strategic fields (STEM, health). UBAINT mobility scholarships for exchange (ARS 3,190,000-4,060,000 depending on region). UBACyT research scholarships for advanced students. Beca de ayuda económica for students who cannot afford study materials. International students should budget approximately $600/month for living expenses in Buenos Aires.'
WHERE name = 'Universidad de Buenos Aires';

-- Part 2: Top 10 majors for Universidad de Buenos Aires
INSERT INTO public.majors (university_id, major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
SELECT u.id, v.major_name, v.acceptance_rate, v.supplemental_requirements, v.subject_ranking, v.ielts_min, v.toefl_min, v.sat_min, v.act_min, v.gpa_min, v.a_level_grades, v.ib_min, v.atar_min, v.duolingo_min, v.pte_min
FROM public.universities u
CROSS JOIN (VALUES
  ('Medicine (Medicina)', NULL, 'Complete CBC (Ciclo Básico Común) with required subjects: Introduction to Biology, Introduction to Chemistry, Introduction to Biophysics, Mathematics, Introduction to Bioethics, and Sociedad y Estado. Spanish proficiency required (all instruction in Spanish). 6-year program leading to Médico degree. Highly competitive by attrition; largest faculty by enrollment (~14,600 CBC inscriptions in 2024).', 'QS #101-150 World (Medicine)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Law (Abogacía)', NULL, 'Complete CBC with required subjects including Introducción al Pensamiento Científico, Introducción al Derecho, and Sociedad y Estado. Spanish proficiency required. 6-year program leading to Abogado degree. UBA Law is ranked in the QS top 50 globally.', 'QS #42 World (Law); #1 Latin America', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Psychology (Psicología)', NULL, 'Complete CBC with required subjects including Introduction to Psychology, Biology, and Sociedad y Estado. Spanish proficiency required. 5-year program leading to Licenciado en Psicología. Second most popular faculty by enrollment (~5,900 CBC inscriptions in 2024).', 'QS #51-100 World (Psychology)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Economics (Economía)', NULL, 'Complete CBC with required subjects including Algebra, Análisis Matemático, Economía, and Sociedad y Estado. Spanish proficiency required. 5-year program at Facultad de Ciencias Económicas. Strong quantitative background recommended.', 'QS #51-100 World (Economics)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Architecture (Arquitectura)', NULL, 'Complete CBC with required subjects including Introducción al Conocimiento Proyectual, Matemática, and Sociedad y Estado. Spanish proficiency required. 6-year program at Facultad de Arquitectura, Diseño y Urbanismo (FADU). Portfolio not required for admission but design aptitude essential.', 'QS #51-100 World (Architecture)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Computer Science (Ciencias de la Computación)', NULL, 'Complete CBC with required subjects including Álgebra, Análisis Matemático, Física, Química, and Sociedad y Estado. Spanish proficiency required. 5-year program at Facultad de Ciencias Exactas y Naturales. Strong mathematics background essential. Data Science and AI programs also available.', 'QS Top 100 World (Data Science & AI); #1 Argentina', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Petroleum Engineering (Ingeniería en Petróleo)', NULL, 'Complete CBC with required subjects including Álgebra, Análisis Matemático, Física, Química, and Sociedad y Estado. Spanish proficiency required. 5-6 year program at Facultad de Ingeniería. Strong mathematics and physics background required. UBA''s highest-ranked program globally.', 'QS #24 World (Petroleum Engineering); #1 Latin America', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Sociology (Sociología)', NULL, 'Complete CBC with required subjects including Introducción al Pensamiento Científico, Sociología, and Sociedad y Estado. Spanish proficiency required. 5-year program at Facultad de Ciencias Sociales. UBA Sociology is ranked in the QS top 50 globally.', 'QS Top 50 World (Sociology); #1 Latin America', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Modern Languages (Letras)', NULL, 'Complete CBC with required subjects including Semiología, Pensamiento Científico, and Sociedad y Estado. Spanish proficiency required. 5-year program at Facultad de Filosofía y Letras. UBA Modern Languages is ranked in the QS top 50 globally. Covers linguistics, literary theory, and literature.', 'QS Top 50 World (Modern Languages); #1 Latin America', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Anthropology (Antropología)', NULL, 'Complete CBC with required subjects including Antropología, Pensamiento Científico, and Sociedad y Estado. Spanish proficiency required. 5-year program at Facultad de Filosofía y Letras. UBA Anthropology is ranked in the QS top 50 globally. Fieldwork components included.', 'QS Top 50 World (Anthropology); #1 Latin America', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
) AS v(major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
WHERE u.name = 'Universidad de Buenos Aires';
