-- Part 1: University-level data for University of Oxford
UPDATE public.universities SET
  website_url = 'https://www.ox.ac.uk',
  tuition_usd = 47000,
  overall_acceptance_rate = '14.1%',
  test_policy = 'Not applicable',
  deadline_calendar = 'UCAS deadline: October 15 (18:00 BST) for all undergraduate courses for the following September entry. Oxford uses a single application deadline with no early action or early decision. Applicants apply through UCAS and may also need to register for admissions tests (e.g. MAT, LNAT, TSA, PAT, BMAT) by separate deadlines. Shortlisted candidates are interviewed in December. Offers released in January. Deferred entry (gap year) applications accepted for most courses. A-Level typical offers range from AAA to A*A*A depending on course. IB typical offers range from 38 to 39 points with 6s and 7s at Higher Level.',
  financial_aid = 'Reach Oxford Scholarship (full tuition, living costs, and return airfare for international students from low-income countries who cannot study in their home country); Clarendon Fund (primarily postgraduate but some undergraduate support); Oxford bursaries for UK Home students with household income under £32,500 (up to £3,500/year non-repayable); Crankstart Scholarships for UK low-income students (up to £5,000/year plus benefits); Moritz-Heyman Scholarships for UK state-school students from disadvantaged backgrounds (£5,000/year plus internship funding); college-specific scholarships and hardship funds available. UK Home students eligible for government tuition fee loans and means-tested maintenance loans. International students should explore country-specific funding and external scholarships.'
WHERE name = 'University of Oxford';

-- Part 2: Delete existing majors for University of Oxford
DELETE FROM public.majors WHERE university_id = (SELECT id FROM public.universities WHERE name = 'University of Oxford');

-- Part 3: Insert top 10 majors for University of Oxford
INSERT INTO public.majors (university_id, major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
SELECT u.id, v.major_name, v.acceptance_rate, v.supplemental_requirements, v.subject_ranking, v.ielts_min, v.toefl_min, v.sat_min, v.act_min, v.gpa_min, v.a_level_grades, v.ib_min, v.atar_min, v.duolingo_min, v.pte_min
FROM public.universities u
CROSS JOIN (VALUES
  ('Economics and Management', '5.5%', 'One of the most competitive courses at Oxford (19.1 applicants per place). A-Level Mathematics required (A* grade). Admissions test: TSA (Thinking Skills Assessment) required. Candidates are assessed on analytical and critical thinking. Interview involves problem-solving and discussion of economic and management concepts. Strong GCSE profile expected (mostly 7-9/A-A*).', 4, 7.0, 110, NULL::int, NULL::int, NULL::numeric, 'A*A*A', 39, NULL::numeric, NULL::int, NULL::int),
  ('Computer Science', '6.4%', 'Highly competitive (17.2 applicants per place). A-Level Mathematics required (A* grade); Further Mathematics strongly recommended. Admissions test: MAT (Mathematics Admissions Test) required. Interview involves mathematical and computational problem-solving. Candidates assessed on logical reasoning, mathematical maturity, and programming aptitude. Strong GCSE profile expected (mostly 7-9/A-A*).', 1, 7.0, 110, NULL::int, NULL::int, NULL::numeric, 'A*A*A', 39, NULL::numeric, NULL::int, NULL::int),
  ('Mathematics and Statistics', '2.1%', 'The most competitive course at Oxford by acceptance rate. A-Level Mathematics required (A* grade); Further Mathematics required (A* grade). Admissions test: MAT (Mathematics Admissions Test) required. Interview focuses on mathematical problem-solving and statistical reasoning. Candidates must demonstrate exceptional mathematical ability. Strong GCSE profile expected (mostly 8-9/A*).', 2, 7.0, 110, NULL::int, NULL::int, NULL::numeric, 'A*A*A', 39, NULL::numeric, NULL::int, NULL::int),
  ('Medicine', '9.0%', 'A-Level Chemistry required plus one of Biology, Physics, or Mathematics. Admissions test: BMAT (BioMedical Admissions Test) / UCAT required. Work experience in healthcare settings expected. Interview assesses scientific knowledge, communication skills, empathy, and motivation for medicine. Six-year course including three years of clinical training. Strong GCSE profile expected (mostly 7-9/A-A*).', 2, 7.5, 110, NULL::int, NULL::int, NULL::numeric, 'A*AA', 39, NULL::numeric, NULL::int, NULL::int),
  ('Law (Jurisprudence)', '9.7%', 'No specific A-Level subjects required but essay-based and analytical subjects valued (e.g. History, English, Languages). Admissions test: LNAT (National Admissions Test for Law) required. Interview assesses analytical reasoning, ability to construct and evaluate arguments, and engagement with legal concepts. Strong GCSE profile expected (mostly 7-9/A-A*).', 1, 7.5, 110, NULL::int, NULL::int, NULL::numeric, 'AAA', 38, NULL::numeric, NULL::int, NULL::int),
  ('Mathematics', '9.5%', 'Highly competitive (10.5 applicants per place). A-Level Mathematics required (A* grade); Further Mathematics required (A* grade). Admissions test: MAT (Mathematics Admissions Test) required. Interview focuses on mathematical problem-solving. Candidates must demonstrate strong mathematical intuition and ability to think creatively. Strong GCSE profile expected (mostly 8-9/A*).', 3, 7.0, 110, NULL::int, NULL::int, NULL::numeric, 'A*A*A', 39, NULL::numeric, NULL::int, NULL::int),
  ('Biomedical Sciences', '8.7%', 'Highly competitive (11.7 applicants per place). A-Level Chemistry required; Biology or another science subject strongly recommended. Admissions test required. Interview assesses scientific reasoning and understanding of biological and chemical concepts. Personal statement should demonstrate genuine interest in biomedical research. Strong GCSE profile expected (mostly 7-9/A-A*).', 6, 7.0, 110, NULL::int, NULL::int, NULL::numeric, 'A*AA', 38, NULL::numeric, NULL::int, NULL::int),
  ('Philosophy, Politics and Economics (PPE)', '12.8%', 'No specific A-Level subjects required but History, Mathematics, Economics, Philosophy, and Politics are valued. Admissions test: TSA (Thinking Skills Assessment) required. Interview assesses analytical thinking across all three disciplines. Candidates must demonstrate breadth of intellectual curiosity and ability to construct reasoned arguments. Strong GCSE profile expected (mostly 7-9/A-A*).', 1, 7.5, 110, NULL::int, NULL::int, NULL::numeric, 'AAA', 39, NULL::numeric, NULL::int, NULL::int),
  ('Physics', '11.4%', 'A-Level Physics and Mathematics required (A* in both preferred). Further Mathematics recommended. Admissions test: PAT (Physics Admissions Test) required. Interview involves physics and mathematical problem-solving. Candidates assessed on ability to apply physical concepts and mathematical techniques. Strong GCSE profile expected (mostly 7-9/A-A*).', 5, 7.0, 110, NULL::int, NULL::int, NULL::numeric, 'A*AA', 39, NULL::numeric, NULL::int, NULL::int),
  ('Engineering Science', '15.0%', 'A-Level Mathematics required (A* grade); Physics required. Further Mathematics recommended. Admissions test: PAT (Physics Admissions Test) required. Interview involves mathematical and engineering problem-solving. Oxford''s Engineering Science programme is a broad four-year MEng covering all engineering disciplines. Strong GCSE profile expected (mostly 7-9/A-A*).', 3, 7.0, 110, NULL::int, NULL::int, NULL::numeric, 'A*A*A', 39, NULL::numeric, NULL::int, NULL::int)
) AS v(major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
WHERE u.name = 'University of Oxford';
