-- Part 1: University-level data for Humboldt-Universität zu Berlin
UPDATE public.universities SET
  website_url = 'https://www.hu-berlin.de/en/',
  tuition_usd = 360,
  overall_acceptance_rate = '~15-25%',
  test_policy = 'Not applicable',
  deadline_calendar = 'Winter semester (Oct start): July 15 (restricted programs via uni-assist), Sept 1 (unrestricted); Summer semester (Apr start): Jan 15. Non-EU applicants must apply through uni-assist portal. Most programs start winter semester only. Medicine and Psychology apply via hochschulstart.de.',
  financial_aid = 'No tuition fees for all students (only ~€330/semester contribution including public transport Deutschlandsemesterticket). Deutschlandstipendium (€300/month merit-based, open to all nationalities). DAAD scholarships for international students. Humboldt-Universität Emergency Aid Fund for students in financial hardship. Erasmus+ grants for EU mobility. Blocked account of ~€11,904/year required for student visa.'
WHERE name = 'Humboldt-Universität zu Berlin';

-- Part 2: Top 10 English-taught and key programs for Humboldt-Universität zu Berlin
INSERT INTO public.majors (university_id, major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
SELECT u.id, v.major_name, v.acceptance_rate, v.supplemental_requirements, v.subject_ranking, v.ielts_min, v.toefl_min, v.sat_min, v.act_min, v.gpa_min, v.a_level_grades, v.ib_min, v.atar_min, v.duolingo_min, v.pte_min
FROM public.universities u
CROSS JOIN (VALUES
  ('European Studies (B.A., English-taught)', '20%', 'Locally restricted admission (NC); taught entirely in English; interdisciplinary program covering EU law, economics, politics, and history; IELTS 6.5 or TOEFL 88 required; motivation letter and CV required; apply via uni-assist', 117, 6.5::numeric, 88, NULL::int, NULL::int, 2.0::numeric, 'AAB', 33, NULL::numeric, 110, 58),
  ('Computer Science (Informatik)', '15%', 'Locally restricted admission (NC); German C1 required (DSH-2 or TestDaF 4x4) for standard track; strong mathematics background essential; programming experience recommended; joint program options available with FU Berlin and TU Berlin via Berlin Mathematical School', NULL::int, NULL::numeric, NULL::int, NULL::int, NULL::int, 2.0::numeric, 'A*AA', 35, NULL::numeric, NULL::int, NULL::int),
  ('Mathematics (Mathematik)', '20%', 'Admission-free (no NC); German C1 required (DSH-2 or TestDaF 4x4); strong secondary school mathematics required; Berlin Mathematical School offers graduate English track; undergraduate is German-taught', NULL::int, NULL::numeric, NULL::int, NULL::int, NULL::int, 2.0::numeric, 'AAB', 34, NULL::numeric, NULL::int, NULL::int),
  ('Physics (Physik)', '20%', 'Admission-free (no NC); German C1 required (DSH-2 or TestDaF 4x4); strong mathematics and physics background required; laboratory work from first semester; some courses available in English at graduate level', NULL::int, NULL::numeric, NULL::int, NULL::int, NULL::int, 2.0::numeric, 'AAB', 34, NULL::numeric, NULL::int, NULL::int),
  ('Economics (Wirtschaftswissenschaften)', '12%', 'Locally restricted admission (NC); German C1 required (DSH-2 or TestDaF 4x4); quantitative aptitude required; some electives available in English; strong analytical skills expected', NULL::int, NULL::numeric, NULL::int, NULL::int, NULL::int, 1.8::numeric, 'A*AA', 36, NULL::numeric, NULL::int, NULL::int),
  ('Philosophy', '25%', 'Admission-free (no NC); German C1 required (DSH-2 or TestDaF 4x4); Latinum may be required for certain specialisations; reading knowledge of French and English expected; covers analytic and continental traditions', NULL::int, NULL::numeric, NULL::int, NULL::int, NULL::int, 2.5::numeric, 'AAB', 33, NULL::numeric, NULL::int, NULL::int),
  ('History (Geschichte)', '20%', 'Locally restricted admission (NC) for some tracks; German C1 required (DSH-2 or TestDaF 4x4); Latinum recommended for ancient and medieval history tracks; strong written analytical skills expected; some seminars in English', NULL::int, NULL::numeric, NULL::int, NULL::int, NULL::int, 2.0::numeric, 'AAA', 35, NULL::numeric, NULL::int, NULL::int),
  ('Law (Rechtswissenschaft)', '10%', 'Locally restricted admission (NC); German C1-C2 required (DSH-2 or TestDaF 4x4); 8-semester Staatsexamen program (no Bachelor/Master structure); strong German language skills essential; international law and moot court activities available in English', NULL::int, NULL::numeric, NULL::int, NULL::int, NULL::int, 1.5::numeric, 'A*A*A', 37, NULL::numeric, NULL::int, NULL::int),
  ('Biology (Biologie)', '18%', 'Locally restricted admission (NC); German C1 required (DSH-2 or TestDaF 4x4); laboratory practical components from first semester; strong secondary chemistry and biology background recommended; research-intensive with links to Museum für Naturkunde', NULL::int, NULL::numeric, NULL::int, NULL::int, NULL::int, 2.0::numeric, 'AAA', 35, NULL::numeric, NULL::int, NULL::int),
  ('Information Management & IT Systems (Wirtschaftsinformatik)', '15%', 'Locally restricted admission (NC); German C1 required (DSH-2 or TestDaF 4x4); combines business administration and computer science; strong quantitative background required; industry partnerships with Berlin tech sector; some electives in English', NULL::int, NULL::numeric, NULL::int, NULL::int, NULL::int, 2.0::numeric, 'A*AA', 35, NULL::numeric, NULL::int, NULL::int)
) AS v(major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
WHERE u.name = 'Humboldt-Universität zu Berlin';
