INSERT INTO public.majors (university_id, major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
SELECT u.id, v.major_name, v.acceptance_rate, v.supplemental_requirements, v.subject_ranking, v.ielts_min, v.toefl_min, v.sat_min, v.act_min, v.gpa_min, v.a_level_grades, v.ib_min, v.atar_min, v.duolingo_min, v.pte_min
FROM public.universities u
CROSS JOIN (VALUES
  ('Computer Science', 2.0, 'Direct-to-major admission required via first-year application to Paul G. Allen School; personal statement and short-response essays; test-optional (SAT/ACT not required)', 'THE #20 World (Computer Science); QS #10 US', 6.0, 76, NULL, NULL, 3.9, 'A*A*A', 38, 99.0, 110, NULL),
  ('Computer Engineering', 2.0, 'Direct-to-major admission required via first-year application to Paul G. Allen School; personal statement and short-response essays; test-optional', 'THE #20 World (Computer Science); QS #10 US (Engineering)', 6.0, 76, NULL, NULL, 3.9, 'A*A*A', 38, 99.0, 110, NULL),
  ('Business Administration', 50.0, 'Direct-to-major or standard admission to Michael G. Foster School of Business; supplemental application with essays on leadership and business interests; test-optional', 'THE #44 World (Business & Economics); US News #23 (Undergraduate Business)', 6.0, 76, NULL, NULL, 3.7, 'AAA', 36, 96.0, 110, NULL),
  ('Mechanical Engineering', 42.0, 'Direct-to-College of Engineering admission preferred; capacity-constrained major; supplemental application after enrollment; strong math and physics coursework required; test-optional', 'QS #51-100 World (Mechanical Engineering)', 6.0, 76, NULL, NULL, 3.75, 'A*AA', 37, 97.0, 110, NULL),
  ('Electrical Engineering', 42.0, 'Direct-to-College of Engineering admission preferred; capacity-constrained major; supplemental application after enrollment; strong math and physics background required; test-optional', 'QS #51-100 World (Electrical & Electronic Engineering)', 6.0, 76, NULL, NULL, 3.75, 'A*AA', 37, 97.0, 110, NULL),
  ('Biology', 43.0, 'College of Arts & Sciences; minimum-requirement major with prerequisite courses in biology, chemistry, and math; test-optional', 'QS #51-100 World (Biological Sciences); THE #22 (Life Sciences)', 6.0, 76, NULL, NULL, 3.6, 'AAA', 35, 95.0, 110, NULL),
  ('Nursing (BSN)', 15.0, 'Capacity-constrained; separate application to School of Nursing required after completing prerequisites; personal statement; clinical experience recommended; test-optional', 'QS #51-100 World (Nursing); US News #1 (Graduate Nursing)', 6.0, 76, NULL, NULL, 3.7, 'A*AA', 37, 97.0, 110, NULL),
  ('Informatics', 28.0, 'Capacity-constrained; direct-to-major or standard admission to the Information School; supplemental application with essays; test-optional', 'QS #23 World (Library & Information Management)', 6.0, 76, NULL, NULL, 3.7, 'AAA', 36, 96.0, 110, NULL),
  ('Economics', 43.0, 'College of Arts & Sciences; minimum-requirement major with prerequisite courses in economics, math, and statistics; test-optional', 'THE #25 World (Social Sciences); QS #51-100 (Economics)', 6.0, 76, NULL, NULL, 3.6, 'AAA', 35, 95.0, 110, NULL),
  ('Psychology', 43.0, 'College of Arts & Sciences; minimum-requirement major with prerequisite courses in psychology and statistics; test-optional', 'THE #43 World (Psychology); QS #51-100 (Psychology)', 6.0, 76, NULL, NULL, 3.6, 'AAA', 35, 95.0, 110, NULL)
) AS v(major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
WHERE u.name = 'University of Washington';
