-- Part 1: University-level data for London School of Economics and Political Science (LSE)
UPDATE public.universities SET
  website_url = 'https://www.lse.ac.uk',
  tuition_usd = 40831,
  overall_acceptance_rate = '6.5%',
  test_policy = 'Not applicable',
  deadline_calendar = 'UCAS deadline: January 29 (18:00 GMT) for September entry. Equal consideration given to all applications received by the deadline. No early action or early decision. Deferred entry (gap year) applications accepted. International qualifications assessed on equivalent basis.',
  financial_aid = 'LSE Undergraduate Support Scheme for overseas students (up to full tuition + maintenance); Uggla Family Scholars Programme (full tuition + living costs for high-need students); LSE named scholarships (various, merit and need-based); Beacon Scholarship; Bluemoon Foundation Scholarship; Singapore LSE Trust Undergraduate Scholarship; Pestalozzi International Scholarship; UK Home students eligible for government tuition fee loans and means-tested maintenance loans. All scholarship applications via single LSE Undergraduate Scholarship Application Form submitted to financial-support@lse.ac.uk.'
WHERE name = 'London School of Economics and Political Science (LSE)';

-- Part 2: Top 10 majors for London School of Economics and Political Science (LSE)
INSERT INTO public.majors (university_id, major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
SELECT u.id, v.major_name, v.acceptance_rate, v.supplemental_requirements, v.subject_ranking, v.ielts_min, v.toefl_min, v.sat_min, v.act_min, v.gpa_min, v.a_level_grades, v.ib_min, v.atar_min, v.duolingo_min, v.pte_min
FROM public.universities u
CROSS JOIN (VALUES
  ('BSc Economics', 6.0, 'A* in A-Level Mathematics required; Further Mathematics desirable (full A-Level or 4th AS); TMUA (Test of Mathematics for University Admission) mandatory; personal statement assessed for analytical reasoning and genuine interest in economics; strong GCSE profile expected (mostly 7-9/A-A*)', 'QS #8 World (Economics & Econometrics)', 7.0, 100, NULL, NULL, 3.7, 'A*AA', 39, 98.0, NULL, 70),
  ('LLB Laws', 5.7, 'LNAT (National Admissions Test for Law) required; no specific A-Level subjects required but essay-based subjects valued; personal statement must demonstrate analytical ability and genuine interest in law; strong GCSE profile expected (mostly 7-9/A-A*)', 'QS #6 World (Law)', 7.0, 100, NULL, NULL, 3.7, 'A*AA', 39, 98.0, NULL, 70),
  ('BSc Accounting and Finance', 9.9, 'A in A-Level Mathematics required; personal statement should demonstrate quantitative aptitude and interest in accounting/finance; strong GCSE profile expected', 'QS #8 World (Accounting & Finance)', 7.0, 100, NULL, NULL, 3.7, 'AAA', 38, 97.0, NULL, 70),
  ('BSc Management', 14.5, 'No specific A-Level subjects required but strong academic subjects preferred; personal statement assessed for leadership potential and interest in management; strong GCSE profile expected', 'QS Top 50 World (Business & Management)', 7.0, 100, NULL, NULL, 3.7, 'AAA', 38, 97.0, NULL, 70),
  ('BSc Philosophy, Politics and Economics', 3.5, 'A in A-Level Mathematics required; strong essay-based subject recommended; personal statement must show genuine interdisciplinary interest across all three disciplines; strong GCSE profile expected (mostly 7-9/A-A*)', 'QS #2 World (Philosophy); QS #5 World (Politics)', 7.0, 100, NULL, NULL, 3.7, 'A*AA', 38, 98.0, NULL, 70),
  ('BSc Finance', 7.8, 'A* in A-Level Mathematics required; Further Mathematics desirable; personal statement should demonstrate strong quantitative skills and interest in financial markets; strong GCSE profile expected', 'QS #8 World (Accounting & Finance)', 7.0, 100, NULL, NULL, 3.7, 'A*AA', 39, 98.0, NULL, 70),
  ('BSc Politics and International Relations', 3.3, 'No specific A-Level subjects required but essay-based subjects (History, Politics, English) highly valued; personal statement must demonstrate genuine engagement with political issues and international affairs; strong GCSE profile expected', 'QS #5 World (Politics & International Studies)', 7.0, 100, NULL, NULL, 3.7, 'AAA', 38, 97.0, NULL, 70),
  ('BSc Politics and Economics', 11.5, 'A in A-Level Mathematics required; essay-based subject recommended; personal statement should show interest in intersection of politics and economics; strong GCSE profile expected', 'QS #5 World (Politics); QS #8 World (Economics)', 7.0, 100, NULL, NULL, 3.7, 'A*AA', 38, 98.0, NULL, 70),
  ('BSc Mathematics and Economics', 7.8, 'A* in A-Level Mathematics required; A-Level Further Mathematics required (or as 4th subject); TMUA recommended; personal statement should demonstrate passion for mathematical approaches to economics', 'QS #8 World (Economics); QS Top 50 (Mathematics)', 7.0, 100, NULL, NULL, 3.7, 'A*A*A', 38, 98.0, NULL, 70),
  ('BSc International Relations', 22.0, 'No specific A-Level subjects required but essay-based subjects (History, Politics, English) highly valued; personal statement must demonstrate genuine engagement with international affairs and global issues; strong GCSE profile expected', 'QS #5 World (Politics & International Studies)', 7.0, 100, NULL, NULL, 3.7, 'AAA', 37, 96.0, NULL, 70)
) AS v(major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
WHERE u.name = 'London School of Economics and Political Science (LSE)';
