-- Part 1: University-level data for Politecnico di Torino
UPDATE public.universities SET
  website_url = 'https://www.polito.it/en',
  tuition_usd = 4700,
  overall_acceptance_rate = '45%',
  test_policy = 'Not applicable',
  deadline_calendar = 'International English-track applicants apply via the Politecnico di Torino online portal. First round: April (for September intake); Second round: June; Third round: August (subject to availability). Some engineering programs require the TOLC-I or TOLC-E admission test (administered by CISIA). Architecture programs may require a design aptitude test. Enrollment confirmation and visa documentation required by July–August.',
  financial_aid = 'Italian public university with income-based tuition (ISEE-Parificato scale): minimum ~€500/year for low-income students, average ~€3,000–5,000/year for international students, maximum ~€5,500/year. EDiSU (regional student services agency) grants: free canteen meals, subsidised housing, and cash grants for eligible low-income students. PoliTO Merit Scholarships for outstanding international students (up to full tuition waiver + €6,000 living allowance). Percorso Eccellenza honours programme with additional funding. EU students may be eligible for home-country loans. Italian Government Scholarships (Ministero degli Affari Esteri) available for international students.'
WHERE name = 'Politecnico di Torino';

-- Part 2: Top 10 majors for Politecnico di Torino
INSERT INTO public.majors (university_id, major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
SELECT u.id, v.major_name, v.acceptance_rate, v.supplemental_requirements, v.subject_ranking, v.ielts_min, v.toefl_min, v.sat_min, v.act_min, v.gpa_min, v.a_level_grades, v.ib_min, v.atar_min, v.duolingo_min, v.pte_min
FROM public.universities u
CROSS JOIN (VALUES
  ('BSc Computer Engineering',      '40%', 'TOLC-I admission test required (administered by CISIA); test covers mathematics, logic, science, and comprehension; minimum score threshold applies; strong secondary school mathematics and physics background essential; apply via Polito online portal; subject area: QS Top 200 World (Computer Science & Information Systems)',             NULL::int, 6.0::numeric, 80::int, NULL::int, NULL::int, 3.0::numeric, 'BBB', 28::int, NULL::numeric, 110::int, 59::int),
  ('BSc Electronic Engineering',    '42%', 'TOLC-I admission test required (CISIA); covers mathematics, logic, science, and comprehension; strong physics and mathematics background required; OFA (additional learning obligations) assigned for students below threshold; subject area: QS Top 300 World (Electrical & Electronic Engineering)',                                   NULL::int, 6.0::numeric, 80::int, NULL::int, NULL::int, 3.0::numeric, 'BBB', 28::int, NULL::numeric, 110::int, 59::int),
  ('BSc Mechanical Engineering',    '45%', 'TOLC-I admission test required (CISIA); strong secondary mathematics and physics background essential; no specific subject prerequisite but calculus-readiness assessed; OFA obligations may be assigned; subject area: QS Top 150 World (Mechanical, Aeronautical & Manufacturing Engineering)',                                   NULL::int, 6.0::numeric, 80::int, NULL::int, NULL::int, 3.0::numeric, 'BBB', 28::int, NULL::numeric, 110::int, 59::int),
  ('BSc Civil Engineering',         '50%', 'TOLC-I admission test required (CISIA); strong mathematics background required; covers geometry, algebra, and trigonometry; program accredited by Italian Ministry of Education (ANVUR); subject area: QS Top 200 World (Civil & Structural Engineering)',                                                                         NULL::int, 6.0::numeric, 80::int, NULL::int, NULL::int, 3.0::numeric, 'BBC', 27::int, NULL::numeric, 105::int, 56::int),
  ('BSc Aerospace Engineering',     '38%', 'TOLC-I admission test required (CISIA); one of the most competitive engineering programs; strong physics and mathematics required; high OFA threshold; unique specialisation in avionics and space systems; subject area: QS Top 200 World (Mechanical, Aeronautical & Manufacturing Engineering)',                             NULL::int, 6.0::numeric, 80::int, NULL::int, NULL::int, 3.0::numeric, 'BBB', 29::int, NULL::numeric, 110::int, 59::int),
  ('BSc Architecture Construction City', '35%', 'English-track architecture program; portfolio submission and motivation letter required; design drawing skills assessed; strong spatial reasoning expected; apply via Polito portal; subject area: QS Top 150 World (Architecture / Built Environment)',                                                                     NULL::int, 6.0::numeric, 80::int, NULL::int, NULL::int, 3.0::numeric, 'BBC', 28::int, NULL::numeric, 105::int, 56::int),
  ('BSc Industrial Design',         '30%', 'Competitive portfolio-based selection in addition to TOLC-E test; portfolio must demonstrate creative and visual problem-solving skills; motivation letter required; design aptitude assessed via test; highly competitive with limited places; subject area: QS Top 200 World (Art & Design)',                                  NULL::int, 6.0::numeric, 80::int, NULL::int, NULL::int, 3.0::numeric, 'BCC', 27::int, NULL::numeric, 100::int, 55::int),
  ('BSc Mathematical Engineering',  '48%', 'TOLC-I admission test required (CISIA); strongest mathematics background required of all engineering programs; covers analysis, linear algebra, and probability; designed for students with exceptional quantitative skills; subject area: QS Top 300 World (Mathematics)',                                                      NULL::int, 6.0::numeric, 80::int, NULL::int, NULL::int, 3.0::numeric, 'ABB', 30::int, NULL::numeric, 110::int, 59::int),
  ('BSc Energy Engineering',        '50%', 'TOLC-I admission test required (CISIA); interdisciplinary program covering thermodynamics, fluid mechanics, and electrical systems; growing demand due to Italy''s energy transition strategy; strong mathematics and physics background required; subject area: QS Top 300 World (Engineering)',                              NULL::int, 6.0::numeric, 80::int, NULL::int, NULL::int, 3.0::numeric, 'BBC', 27::int, NULL::numeric, 105::int, 56::int),
  ('BSc Biomedical Engineering',    '35%', 'TOLC-I or TOLC-B admission test required (CISIA); strong mathematics and biology/chemistry background recommended; program bridges engineering with life sciences; limited places in English-track; one of the more selective PoliTo engineering programs; subject area: QS Top 300 World (Engineering — Biomedical)',           NULL::int, 6.0::numeric, 80::int, NULL::int, NULL::int, 3.0::numeric, 'BBB', 28::int, NULL::numeric, 110::int, 59::int)
) AS v(major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
WHERE u.name = 'Politecnico di Torino';
