-- Part 1: University-level data for Imperial College London
UPDATE public.universities SET
  website_url = 'https://www.imperial.ac.uk',
  tuition_usd = 46250,
  overall_acceptance_rate = '14.3%',
  test_policy = 'Not applicable',
  deadline_calendar = 'UCAS equal consideration deadline: January 29 (18:00 GMT) for most programmes. Medicine (MBBS): October 15 (18:00 GMT). All applications via UCAS. No early action or early decision. Deferred entry (gap year) applications accepted for most programmes except Medicine. International qualifications assessed on equivalent basis. Admissions tests: ESAT required for Engineering; TMUA required for Computing, Mathematics, and Economics; UCAT required for Medicine. Interviews required for Medicine, Computing, and some Engineering programmes.',
  financial_aid = 'President''s Undergraduate Scholarships: up to £10,000 per year fee reduction (merit-based, renewable for duration of degree). Imperial Bursary: up to £5,000 per year for UK students from low-income households. President''s PhD Scholarships also available. International students may apply for external scholarships including Chevening, Commonwealth, and country-specific government scholarships. Imperial College Trust funding for students facing financial hardship. US Federal Direct Loans accepted. Limited number of departmental scholarships and prizes available. No need-blind admissions for international students.'
WHERE name = 'Imperial College London';

-- Part 2: Top 10 majors for Imperial College London
-- First delete existing majors
DELETE FROM public.majors WHERE university_id = (SELECT id FROM public.universities WHERE name = 'Imperial College London');

-- Then insert updated majors with full data
INSERT INTO public.majors (university_id, major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
SELECT u.id, v.major_name, v.acceptance_rate, v.supplemental_requirements, v.subject_ranking, v.ielts_min, v.toefl_min, v.sat_min, v.act_min, v.gpa_min, v.a_level_grades, v.ib_min, v.atar_min, v.duolingo_min, v.pte_min
FROM public.universities u
CROSS JOIN (VALUES
  ('Computing (MEng/BEng)', '16%', 'TMUA (Test of Mathematics for University Admission) required; A* in A-Level Mathematics essential; interview required; personal statement assessed for programming experience and genuine interest in computing; Further Mathematics recommended but not required; GCSE profile considered. QS #14 World (Computer Science & Information Systems).', 14, 6.5, 92, NULL::integer, NULL::integer, NULL::numeric, 'A*A*A', 41, NULL::numeric, 115, 62),
  ('Medicine (MBBS)', '13%', 'UCAT admissions test required; A-Levels must include Biology and Chemistry (both at grade A minimum); Multiple Mini Interviews (MMI) required; work experience in healthcare setting expected; UCAS deadline October 15; 6-year programme with integrated BSc; DBS check and occupational health clearance required; GCSE minimum 7/A in English, Mathematics, and sciences. QS #10 World (Medicine).', 10, 7.0, 100, NULL::integer, NULL::integer, NULL::numeric, 'AAA', 38, NULL::numeric, 125, 69),
  ('Mechanical Engineering (MEng)', '18%', 'ESAT admissions test required (Mathematics 1, Mathematics 2, Physics components); A* in Mathematics and A/A* in Physics at A-Level required; Further Mathematics strongly recommended; e-interview may be required; accredited by IMechE; 4-year integrated Masters programme. QS #9 World (Mechanical Engineering).', 9, 6.5, 92, NULL::integer, NULL::integer, NULL::numeric, 'A*A*A', 40, NULL::numeric, 115, 62),
  ('Mathematics (MSci/BSc)', '17%', 'TMUA (Test of Mathematics for University Admission) required; A* in Mathematics and A* in Further Mathematics at A-Level required; strong problem-solving ability assessed through admissions test; personal statement should demonstrate passion for mathematics beyond syllabus. QS #12 World (Mathematics).', 12, 6.5, 92, NULL::integer, NULL::integer, NULL::numeric, 'A*A*A', 39, NULL::numeric, 115, 62),
  ('Electrical and Electronic Engineering (MEng)', '29%', 'ESAT admissions test required (Mathematics 1, Mathematics 2, Physics components); A* in Mathematics and A/A* in Physics at A-Level required; Further Mathematics strongly encouraged; online interview may be required; accredited by IET; 4-year integrated Masters programme. QS #14 World (Electrical & Electronic Engineering).', 14, 6.5, 92, NULL::integer, NULL::integer, NULL::numeric, 'A*A*A', 40, NULL::numeric, 115, 62),
  ('Chemical Engineering (MEng)', '44%', 'ESAT admissions test required (Mathematics 1, Mathematics 2, Chemistry components); A* in Chemistry and A* in Mathematics at A-Level required; accredited by IChemE; strong industry links; 4-year integrated Masters programme with option for year in industry. QS #7 World (Chemical Engineering).', 7, 6.5, 92, NULL::integer, NULL::integer, NULL::numeric, 'A*A*A', 40, NULL::numeric, 115, 62),
  ('Economics, Finance and Data Science (BSc)', '7%', 'TMUA (Test of Mathematics for University Admission) required; A* in A-Level Mathematics essential; online interview required; highly competitive programme jointly offered by Imperial College Business School and Department of Mathematics; personal statement should demonstrate quantitative aptitude and interest in economics/finance. QS #15 World (Economics & Econometrics).', 15, 7.0, 100, NULL::integer, NULL::integer, NULL::numeric, 'A*AA', 39, NULL::numeric, 125, 69),
  ('Aeronautical Engineering (MEng)', '20%', 'ESAT admissions test required (Mathematics 1, Mathematics 2, Physics components); A* in Mathematics and A/A* in Physics at A-Level required; Further Mathematics recommended; e-interview required; accredited by Royal Aeronautical Society; 4-year integrated Masters programme. QS #9 World (Mechanical, Aeronautical & Manufacturing Engineering).', 9, 6.5, 92, NULL::integer, NULL::integer, NULL::numeric, 'A*A*A', 40, NULL::numeric, 115, 62),
  ('Biochemistry (BSc)', '29%', 'A-Levels must include Chemistry and one of Biology, Mathematics, or Physics; no admissions test required for 2026 entry; personal statement should demonstrate genuine interest in molecular biosciences; practical laboratory skills developed from year one. QS #21 World (Biological Sciences).', 21, 6.5, 92, NULL::integer, NULL::integer, NULL::numeric, 'AAA', 38, NULL::numeric, 115, 62),
  ('Physics (MSci/BSc)', '35%', 'A-Levels must include Mathematics (A*) and Physics (A*); Further Mathematics recommended; no admissions test required for 2026 entry; personal statement should demonstrate passion for physics and awareness of current research; 4-year MSci includes substantial research project. QS #11 World (Physics & Astronomy).', 11, 6.5, 92, NULL::integer, NULL::integer, NULL::numeric, 'A*A*A', 40, NULL::numeric, 115, 62)
) AS v(major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
WHERE u.name = 'Imperial College London';
