-- Part 1: University-level data for National University of Singapore (NUS)
UPDATE public.universities SET
  website_url = 'https://www.nus.edu.sg',
  tuition_usd = 25500,
  overall_acceptance_rate = '5%',
  test_policy = 'SAT accepted (min 600 Reading & Writing, 650 Math) or ACT with Writing accepted (min composite 29, writing 8), each paired with at least 3 AP courses. Alternatively, 5 AP courses alone (including Calculus BC). IB Diploma accepted (no specific minimum published). A-Levels accepted. IELTS min 6.5 or TOEFL iBT min 92 required if prior education not in English.',
  deadline_calendar = 'International qualifications: December 3 to February 23. IB Diploma: December 17 to February 23. Singapore A-Levels: late February to March 19. Single annual intake in August. Admissions outcomes released May to July.',
  financial_aid = 'NUS International Undergraduate Scholarship (100% subsidised tuition after MOE Tuition Grant, S$5,800 annual living allowance, S$1,750 one-time computer allowance); ASEAN Undergraduate Scholarship (full tuition, S$5,800 living allowance); Science & Technology Undergraduate Scholarship (full tuition, S$6,000 living allowance); NUS Global Merit Scholarship (full tuition, S$6,000 living allowance, S$2,000 computer allowance, overseas exchange support); MOE Tuition Grant available to all international students (reduces fees by 40-60%, requires 3-year work bond in Singapore); NUS Bursaries and Study Loans also available.'
WHERE name = 'National University of Singapore (NUS)';

-- Part 2: Top 10 majors for National University of Singapore (NUS)
DELETE FROM public.majors WHERE university_id = (SELECT id FROM public.universities WHERE name = 'National University of Singapore (NUS)');

INSERT INTO public.majors (university_id, major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
SELECT u.id, v.major_name, v.acceptance_rate, v.supplemental_requirements, v.subject_ranking, v.ielts_min, v.toefl_min, v.sat_min, v.act_min, v.gpa_min, v.a_level_grades, v.ib_min, v.atar_min, v.duolingo_min, v.pte_min
FROM public.universities u
CROSS JOIN (VALUES
  ('Computer Science', '4%', 'SAT min 600 R&W + 650 Math (or ACT composite 29 with Writing 8) plus at least 3 AP courses including Calculus BC required; strong mathematics and computing aptitude expected; portfolio of programming projects recommended; IELTS 6.5 or TOEFL 92 if prior education not in English', 4, 6.5, 92, 1250, 29, 3.5, 'AAA/A*AA', 36, NULL::numeric, NULL::integer, NULL::integer),
  ('Business Administration (BBA)', '8%', 'SAT min 600 R&W + 650 Math (or ACT composite 29 with Writing 8) plus at least 3 AP courses including Calculus BC required; personal essay and co-curricular achievements assessed; strong quantitative and communication skills expected', 8, 6.5, 92, 1250, 29, 3.5, 'AAA', 36, NULL::numeric, NULL::integer, NULL::integer),
  ('Mechanical Engineering', '7%', 'SAT min 600 R&W + 650 Math (or ACT composite 29 with Writing 8) plus at least 3 AP courses including Calculus BC required; strong foundation in mathematics and physics; H2 Mathematics and H2 Physics at A-Level preferred', 15, 6.5, 92, 1250, 29, 3.5, 'AAA', 36, NULL::numeric, NULL::integer, NULL::integer),
  ('Chemical Engineering', '6%', 'SAT min 600 R&W + 650 Math (or ACT composite 29 with Writing 8) plus at least 3 AP courses including Calculus BC required; strong foundation in mathematics, chemistry, and physics expected; H2 Chemistry and H2 Mathematics at A-Level preferred', 4, 6.5, 92, 1250, 29, 3.5, 'AAA', 36, NULL::numeric, NULL::integer, NULL::integer),
  ('Civil & Structural Engineering', '8%', 'SAT min 600 R&W + 650 Math (or ACT composite 29 with Writing 8) plus at least 3 AP courses including Calculus BC required; strong mathematics and physics background expected; H2 Mathematics at A-Level required', 3, 6.5, 92, 1250, 29, 3.5, 'AAA', 36, NULL::numeric, NULL::integer, NULL::integer),
  ('Electrical & Electronic Engineering', '6%', 'SAT min 600 R&W + 650 Math (or ACT composite 29 with Writing 8) plus at least 3 AP courses including Calculus BC required; strong mathematics and physics foundation expected; H2 Mathematics and H2 Physics at A-Level preferred', 4, 6.5, 92, 1250, 29, 3.5, 'AAA', 36, NULL::numeric, NULL::integer, NULL::integer),
  ('Economics', '5%', 'SAT min 600 R&W + 650 Math (or ACT composite 29 with Writing 8) plus at least 3 AP courses including Calculus BC required; strong quantitative reasoning and analytical skills expected; H2 Mathematics at A-Level required; BSocSci (Hons) in Economics under College of Humanities and Sciences', 15, 6.5, 92, 1250, 29, 3.5, 'AAA/A*AA', 36, NULL::numeric, NULL::integer, NULL::integer),
  ('Law (LLB)', '3%', 'SAT min 600 R&W + 650 Math (or ACT composite 29 with Writing 8) plus at least 3 AP courses required (Calculus BC not mandatory for Law); outstanding academic record and strong analytical writing skills required; personal statement and co-curricular record assessed; interview may be required', 7, 7.0, 100, 1350, 29, 3.7, 'AAA/A*AA', 38, NULL::numeric, NULL::integer, NULL::integer),
  ('Medicine (MBBS)', '2%', 'SAT min 600 R&W + 650 Math (or ACT composite 29 with Writing 8) plus at least 3 AP courses including Calculus BC required; strong foundation in biology and chemistry; BMAT or equivalent aptitude test may be required; interview mandatory; H2 Chemistry and H2 Biology/Physics at A-Level required', 22, 6.5, 92, 1350, 29, 3.8, 'A*A*A/AAA', 38, NULL::numeric, NULL::integer, NULL::integer),
  ('Data Science and Analytics', '5%', 'SAT min 600 R&W + 650 Math (or ACT composite 29 with Writing 8) plus at least 3 AP courses including Calculus BC required; strong foundation in mathematics and statistics; programming aptitude assessed; H2 Mathematics at A-Level required; interdisciplinary programme under College of Humanities and Sciences', 4, 6.5, 92, 1250, 29, 3.5, 'AAA', 36, NULL::numeric, NULL::integer, NULL::integer)
) AS v(major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
WHERE u.name = 'National University of Singapore (NUS)';
