-- Part 1: University-level data for Ruprecht-Karls-Universität Heidelberg
UPDATE public.universities SET
  website_url = 'https://www.uni-heidelberg.de/en/',
  tuition_usd = 3600,
  overall_acceptance_rate = '~15-20%',
  test_policy = 'Not applicable',
  deadline_calendar = 'Winter semester (Oct start): July 15; Summer semester (Apr start): January 15. Non-EU applicants apply via uni-assist for credential evaluation. Restricted programs may close earlier. International applicants outside EU/EEA pay €1,500/semester tuition fee (Baden-Württemberg state policy) in addition to ~€161 semester contribution.',
  financial_aid = 'No general tuition fees for EU/EEA students (only ~€161/semester Semesterbeitrag). Non-EU/EEA students pay €1,500/semester (€3,000/year) tuition as of Baden-Württemberg 2017 policy. Heidelberg Excellence Initiative scholarships; Deutschlandstipendium (€300/month merit-based); DAAD scholarships; Ruprecht-Karls-Stiftung grants; Heidehilfe emergency aid fund. Blocked account of ~€11,904/year required for student visa.'
WHERE name = 'Ruprecht-Karls-Universität Heidelberg';

-- Part 2: Top 10 majors for Ruprecht-Karls-Universität Heidelberg
INSERT INTO public.majors (university_id, major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
SELECT u.id, v.major_name, v.acceptance_rate, v.supplemental_requirements, v.subject_ranking, v.ielts_min, v.toefl_min, v.sat_min, v.act_min, v.gpa_min, v.a_level_grades, v.ib_min, v.atar_min, v.duolingo_min, v.pte_min
FROM public.universities u
CROSS JOIN (VALUES
  ('International Health (B.Sc.)', '~20%', 'One of the few fully English-taught bachelor''s programs at Heidelberg; NC-restricted with ~40 places per cohort; interview required; prior experience in health/development sector preferred; IELTS 6.5 or TOEFL 90 required; German not required but recommended', 7::int, 6.5::numeric, 90::int, NULL::int, NULL::int, 3.3::numeric, 'AAA', 33::int, NULL::numeric, 110::int, 65::int),
  ('English Studies (B.A.)', '~35%', 'Admission via entrance examination (Eignungsprüfung); program can be completed fully in English; language test required for non-native speakers; covers linguistics, literary studies, and cultural studies; IB English A HL recommended', 101::int, 6.5::numeric, 90::int, NULL::int, NULL::int, 3.0::numeric, 'AAB', 33::int, NULL::numeric, 105::int, 62::int),
  ('Medicine (Medizin / Staatsexamen)', '~3%', 'Extremely competitive NC (~1.0 Abitur equivalent); apply via hochschulstart.de; German C1-C2 required (DSH-2 or TestDaF 4x4); 6-year Staatsexamen program; TMS medical aptitude test recommended; among the best medical faculties in Germany', 55::int, NULL::numeric, NULL::int, NULL::int, NULL::int, 1.0::numeric, 'A*A*A*', 40::int, NULL::numeric, NULL::int, NULL::int),
  ('Molecular Biotechnology (B.Sc.)', '~8%', 'NC-restricted with ~60 places; German C1-C2 required (DSH-2 or TestDaF 4x4); strong chemistry and biology background required; laboratory practical skills advantageous; affiliated with German Cancer Research Center (DKFZ)', 55::int, NULL::numeric, NULL::int, NULL::int, NULL::int, 1.5::numeric, 'A*A*A', 38::int, NULL::numeric, NULL::int, NULL::int),
  ('Physics (B.Sc.)', '~20%', 'Admission-free (no NC) but highly demanding; German C1-C2 required (DSH-2 or TestDaF 4x4); strong mathematics background essential; access to Heidelberg Institute for Theoretical Studies (HITS) and European XFEL collaborations', 75::int, NULL::numeric, NULL::int, NULL::int, NULL::int, 2.0::numeric, 'A*AA', 36::int, NULL::numeric, NULL::int, NULL::int),
  ('Economics (B.Sc.)', '~15%', 'NC-restricted with ~180 places; German C1-C2 required (DSH-2 or TestDaF 4x4); strong mathematics background required; aptitude assessment for mathematics may apply; apply via uni-assist for international qualifications', 175::int, NULL::numeric, NULL::int, NULL::int, NULL::int, 1.8::numeric, 'A*AA', 37::int, NULL::numeric, NULL::int, NULL::int),
  ('Political Science (B.A.)', '~18%', 'NC-restricted; German C1-C2 required (DSH-2 or TestDaF 4x4); covers comparative politics, international relations, and political theory; Heidelberg Institute for Political Science is highly regarded; some seminars offered in English', 75::int, NULL::numeric, NULL::int, NULL::int, NULL::int, 2.0::numeric, 'AAA', 36::int, NULL::numeric, NULL::int, NULL::int),
  ('Psychology (B.Sc.)', '~5%', 'Highly competitive NC (~1.2-1.4 Abitur equivalent); apply via hochschulstart.de; German C1-C2 required (DSH-2 or TestDaF 4x4); strong natural sciences background recommended; one of Germany''s oldest psychology faculties', 75::int, NULL::numeric, NULL::int, NULL::int, NULL::int, 1.3::numeric, 'A*A*A', 39::int, NULL::numeric, NULL::int, NULL::int),
  ('Philosophy (B.A.)', '~30%', 'Admission-free (no NC); German C1-C2 required (DSH-2 or TestDaF 4x4); Latinum or Graecum may be required for ancient philosophy tracks; neo-Kantian heritage dating to 1386 founding', 75::int, NULL::numeric, NULL::int, NULL::int, NULL::int, 2.5::numeric, 'AAB', 34::int, NULL::numeric, NULL::int, NULL::int),
  ('Computer Science (B.Sc.)', '~12%', 'NC-restricted; German C1-C2 required (DSH-2 or TestDaF 4x4); strong mathematics and programming background expected; collaboration with Heidelberg Institute for Theoretical Studies and SAP SE; aptitude assessment may apply', 225::int, NULL::numeric, NULL::int, NULL::int, NULL::int, 1.8::numeric, 'A*AA', 37::int, NULL::numeric, NULL::int, NULL::int)
) AS v(major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
WHERE u.name = 'Ruprecht-Karls-Universität Heidelberg';
