-- Part 1: University-level data for University of Basel
UPDATE public.universities SET
  website_url = 'https://www.unibas.ch/en',
  tuition_usd = 1900,
  overall_acceptance_rate = '50%',
  test_policy = 'Not applicable',
  deadline_calendar = 'Application portal opens February; non-Swiss/non-EU applicants must apply by April 30 for the autumn semester (September entry). Swiss Matura holders admitted automatically to most programmes. International applicants require credential evaluation by the Admissions Office. No spring intake for most bachelor programmes.',
  financial_aid = 'Very low tuition by design (~CHF 850/semester = ~CHF 1,700/year for all students, domestic and international alike). University of Basel Excellence Scholarships for outstanding Master''s students. Government Excellence Scholarships (Swiss Confederation) available to international students for postgraduate study. Erasmus+ exchange grants. Swiss-European Mobility Programme. No need-based aid for bachelor students; students are expected to cover living costs (~CHF 2,000/month in Basel). Blocked account or proof of funds required for non-EU student visa (~CHF 24,000/year).'
WHERE name = 'University of Basel';

-- Part 2: Top 10 majors for University of Basel
INSERT INTO public.majors (university_id, major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
SELECT u.id, v.major_name, v.acceptance_rate, v.supplemental_requirements, v.subject_ranking, v.ielts_min, v.toefl_min, v.sat_min, v.act_min, v.gpa_min, v.a_level_grades, v.ib_min, v.atar_min, v.duolingo_min, v.pte_min
FROM public.universities u
CROSS JOIN (VALUES
  ('BSc Nanosciences', NULL, 'Flagship English-taught bachelor programme; unique interdisciplinary programme combining physics, chemistry, and biology at the nanoscale; strong background in mathematics, physics and chemistry required; programme taught entirely in English; admission based on secondary school qualifications; no entrance exam', 'QS Top 100 World (Physics); unique programme in Switzerland', 6.0, 80, NULL, NULL, NULL, 'ABB (Maths + Sciences required)', 30, NULL, NULL, NULL),
  ('BSc Biology', NULL, 'Taught primarily in German; strong background in biology, chemistry, and mathematics required; international students must demonstrate German B2 proficiency for German-medium courses; some courses available in English; broad programme covering cell biology, genetics, ecology, and evolution', 'QS #158 World (Life Sciences & Medicine)', NULL, NULL, NULL, NULL, NULL, 'ABB (Sciences required)', 30, NULL, NULL, NULL),
  ('BSc Chemistry', NULL, 'Taught primarily in German; strong background in chemistry, mathematics, and physics required; German B2 proficiency required; laboratory-intensive programme; Basel is a global hub for pharmaceutical and chemical industries (Novartis, Roche HQ)', 'QS #158 World (Chemistry)', NULL, NULL, NULL, NULL, NULL, 'ABB (Chemistry + Maths required)', 30, NULL, NULL, NULL),
  ('BSc Medicine (Humanmedizin)', 15.0, 'Taught in German; 6-year MD programme; mandatory numerus clausus entrance exam (EMS - Eignungstest fur das Medizinstudium) for Swiss and EU applicants; German C1 proficiency required; strong background in biology, chemistry, and physics required; highly competitive', 'QS Top 200 World (Medicine)', NULL, NULL, NULL, NULL, NULL, 'A*AA (Sciences required)', 36, NULL, NULL, NULL),
  ('BSc Psychology', NULL, 'Taught primarily in German; German B2 proficiency required; broad scientific psychology curriculum covering cognitive, social, developmental, and clinical psychology; strong mathematics and statistics component; no entrance exam beyond credential evaluation', 'QS Top 200 World (Psychology)', NULL, NULL, NULL, NULL, NULL, 'ABB', 30, NULL, NULL, NULL),
  ('BSc Mathematics', NULL, 'Taught primarily in German; strong A-Level or equivalent mathematics background required; German B2 proficiency required; covers pure mathematics, applied mathematics, and statistics; research-oriented curriculum', 'QS Top 200 World (Mathematics)', NULL, NULL, NULL, NULL, NULL, 'A*AB (Maths required)', 32, NULL, NULL, NULL),
  ('BSc Physics', NULL, 'Taught primarily in German; strong background in physics and mathematics required; German B2 proficiency required; covers classical mechanics, electrodynamics, quantum mechanics, and statistical mechanics; access to Swiss Nanoscience Institute facilities', 'QS Top 200 World (Physics & Astronomy)', NULL, NULL, NULL, NULL, NULL, 'ABB (Maths + Physics required)', 30, NULL, NULL, NULL),
  ('BSc Computer Science', NULL, 'Taught primarily in German; German B2 proficiency required; strong mathematics and logic background required; programme covers algorithms, software engineering, artificial intelligence, and theoretical computer science; some courses available in English at master level', 'QS Top 300 World (Computer Science & Information Systems)', NULL, NULL, NULL, NULL, NULL, 'ABB (Maths required)', 30, NULL, NULL, NULL),
  ('BSc African Studies (Afrikastudien)', NULL, 'Taught partly in English and German; one of the few English-medium bachelor programmes; interdisciplinary programme covering African history, politics, cultures, and languages; German A2 proficiency recommended but not mandatory for English track; unique programme in the German-speaking world', 'Leading centre for African Studies in German-speaking Europe', 6.0, 80, NULL, NULL, NULL, 'ABB', 30, NULL, NULL, NULL),
  ('BA Philosophy', NULL, 'Taught primarily in German; German B2 proficiency required; broad curriculum covering analytic and continental philosophy, logic, ethics, and history of philosophy; single-subject or combined degree with other humanities disciplines available; research-oriented with strong ties to Basel''s humanities faculty', 'QS Top 200 World (Philosophy)', NULL, NULL, NULL, NULL, NULL, 'ABB', 30, NULL, NULL, NULL)
) AS v(major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
WHERE u.name = 'University of Basel';
