-- Part 1: University-level data for Lancaster University
UPDATE public.universities SET
  website_url = 'https://www.lancaster.ac.uk/',
  tuition_usd = 34620,
  overall_acceptance_rate = '18.69%',
  test_policy = 'Not applicable',
  deadline_calendar = 'UCAS equal consideration deadline: January 14 (18:00 UK time). Medicine (MBChB): October 15 (18:00 UK time). UCAS Extra available from late February for applicants with no offers. Clearing opens in July. International applicants encouraged to apply well before the deadline. Deferred entry accepted for most programmes.',
  financial_aid = 'Lancaster Global Scholarships: international undergraduate scholarships covering up to full tuition fees, awarded on academic merit. Vice-Chancellor Scholarship for international students. GREAT Scholarships available in partnership with the British Council for students from eligible countries. Country-specific bursaries (e.g. for students from India, China, South and Southeast Asia). Lancaster Management School scholarships for high-achieving business applicants. Lancaster Achievement Award for UK/EU students with financial need. UK government Tuition Fee Loans and Maintenance Loans available for home students. Santander Scholarships partnership. Full scholarship listings available at lancaster.ac.uk/study/fees-and-funding/scholarships-and-bursaries/.'
WHERE name = 'Lancaster University';

-- Part 2: Top 10 majors for Lancaster University
INSERT INTO public.majors (university_id, major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
SELECT u.id, v.major_name, v.acceptance_rate, v.supplemental_requirements, v.subject_ranking, v.ielts_min, v.toefl_min, v.sat_min, v.act_min, v.gpa_min, v.a_level_grades, v.ib_min, v.atar_min, v.duolingo_min, v.pte_min
FROM public.universities u
CROSS JOIN (VALUES
  ('BSc Accounting and Finance', '19%', 'A-level Mathematics required (grade B minimum); personal statement should demonstrate interest in accounting, finance and business; UCAS points considered holistically; accredited by ICAEW, ACCA, CIMA, and CIPFA — graduates can claim up to 9 exemptions. Lancaster Management School holds triple accreditation (AACSB, AMBA, EQUIS).', NULL::integer, 6.5::numeric, 87, NULL::integer, NULL::integer, NULL::numeric, 'AAA', 36, NULL::numeric, 110, 65),
  ('BSc Business Management', '22%', 'No specific A-level subject requirements; personal statement must demonstrate interest in management, leadership, and analytical thinking; UCAS points assessed holistically; Lancaster Management School is triple-accredited (AACSB, AMBA, EQUIS). Work experience or extracurricular involvement valued.', NULL::integer, 6.5::numeric, 87, NULL::integer, NULL::integer, NULL::numeric, 'ABB', 32, NULL::numeric, 110, 65),
  ('BSc Computer Science', '30%', 'A-level Mathematics required (grade A); A-level Further Mathematics or Physics desirable but not required; personal statement should demonstrate programming experience or genuine interest in computing; no specific programming language knowledge required for entry.', NULL::integer, 6.5::numeric, 87, NULL::integer, NULL::integer, NULL::numeric, 'AAB', 34, NULL::numeric, 110, 65),
  ('BA Law', '18%', 'No specific A-level subjects required but essay-based subjects (History, Politics, English) strongly preferred; personal statement must demonstrate analytical ability, genuine interest in law, and awareness of current legal issues; LNAT not required; accredited by Bar Standards Board and Solicitors Regulation Authority.', NULL::integer, 7.0::numeric, 95, NULL::integer, NULL::integer, NULL::numeric, 'ABB', 33, NULL::numeric, 120, 68),
  ('BSc Economics', '20%', 'A-level Mathematics required (grade B); personal statement should show genuine interest in economic theory and its application to real-world issues; Further Mathematics desirable but not required; strong GCSE Mathematics profile expected.', NULL::integer, 6.5::numeric, 87, NULL::integer, NULL::integer, NULL::numeric, 'ABB', 33, NULL::numeric, 110, 65),
  ('BSc Psychology', '25%', 'No specific A-level subject requirements; A-level in a science subject (Biology, Chemistry, Mathematics, or Physics) is preferred; personal statement must demonstrate understanding of psychology as a scientific discipline; BPS-accredited programme.', NULL::integer, 6.5::numeric, 87, NULL::integer, NULL::integer, NULL::numeric, 'ABB', 32, NULL::numeric, 110, 65),
  ('MEng / BEng Engineering', '35%', 'A-level Mathematics required (grade A); A-level Physics required (grade B); personal statement should demonstrate interest in engineering and problem-solving; accredited by relevant professional bodies (IET, IMechE, RAeS depending on pathway). MEng requires higher grades than BEng.', NULL::integer, 6.5::numeric, 87, NULL::integer, NULL::integer, NULL::numeric, 'AAB', 34, NULL::numeric, 110, 65),
  ('BA Politics', '28%', 'No specific A-level subject requirements; essay-based subjects (History, Politics, English, Sociology) valued; personal statement should demonstrate critical thinking, awareness of political issues, and genuine interest in political theory and international relations.', NULL::integer, 6.5::numeric, 87, NULL::integer, NULL::integer, NULL::numeric, 'ABB', 32, NULL::numeric, 110, 65),
  ('BSc Data Science', '28%', 'A-level Mathematics required (grade A); A-level Further Mathematics, Statistics, or Computer Science desirable; personal statement should demonstrate quantitative aptitude, interest in data analysis, and any relevant coding or statistical experience; joint degree with computing and statistics.', NULL::integer, 6.5::numeric, 87, NULL::integer, NULL::integer, NULL::numeric, 'AAB', 34, NULL::numeric, 110, 65),
  ('BA English Literature', '30%', 'A-level English Literature required (grade A or B depending on pathway); personal statement must demonstrate wide independent reading beyond school curriculum, analytical ability, and genuine passion for literature; writing sample or portfolio not required at application stage.', NULL::integer, 6.5::numeric, 87, NULL::integer, NULL::integer, NULL::numeric, 'ABB', 32, NULL::numeric, 110, 65)
) AS v(major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
WHERE u.name = 'Lancaster University';
