-- Part 1: Update university-level data for University of Porto
UPDATE public.universities SET
  website_url = 'https://www.up.pt/portal/en/',
  tuition_usd = 7700,
  overall_acceptance_rate = '45-55%',
  test_policy = 'Not applicable',
  deadline_calendar = 'Non-EU international students apply via the University of Porto international application portal (general deadline: May 31 for September start; some faculties have earlier deadlines in April). EU/EEA students apply via national Concurso Nacional de Acesso (typically March-July). Erasmus and exchange students follow bilateral agreement deadlines (March 31 for autumn semester). Direct admission applications to individual faculties may vary. Late applications sometimes accepted until late July subject to places.',
  financial_aid = 'Tuition approximately €7,000/year (~$7,700 USD) for non-EU international undergraduate students (EU/EEA students pay ~€697/year national social fee). University of Porto Merit Scholarships for outstanding international students. FCT (Fundacao para a Ciencia e a Tecnologia) scholarships available at postgraduate level. Erasmus+ grants for incoming exchange students (~€520-800/month depending on origin country). IPMA (Instituto Politecnico) needs-based support. Portuguese Government grants via DGES for eligible students. Some bilateral scholarships available through Camoes Institute. Students from Portuguese-speaking countries (CPLP) may qualify for reduced fees under reciprocity agreements.'
WHERE name = 'University of Porto';

-- Part 2: Insert top 10 majors for University of Porto
INSERT INTO public.majors (
  university_id, major_name, acceptance_rate, supplemental_requirements,
  subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min,
  a_level_grades, ib_min, atar_min, duolingo_min, pte_min
)
SELECT
  u.id,
  v.major_name, v.acceptance_rate, v.supplemental_requirements,
  v.subject_ranking, v.ielts_min, v.toefl_min, v.sat_min, v.act_min, v.gpa_min,
  v.a_level_grades, v.ib_min, v.atar_min, v.duolingo_min, v.pte_min
FROM public.universities u
CROSS JOIN (VALUES
  ('Bachelor in Industrial Engineering and Management (English-taught)', NULL::numeric, 'QS Top 300 World (Engineering - Mechanical). Taught entirely in English at FEUP (Faculty of Engineering). Apply via University of Porto international application portal by May 31. Strong background in Mathematics and Physics required. Interview may be required for borderline applicants. 3-year integrated BSc/MSc pathway available.', NULL::integer, 6.0::numeric, 80, NULL::integer, NULL::integer, 3.0::numeric, 'ABB', 30, NULL::numeric, 100, 60),
  ('Bachelor in Informatics and Computing Engineering (English-taught)', NULL::numeric, 'QS Top 400 World (Computer Science & Information Systems). Taught entirely in English at FEUP (Faculty of Engineering). Apply via international portal by May 31. Strong Mathematics background essential. Programming aptitude assessed. One of the most competitive programs at U.Porto. Leads to BSc+MSc integrated degree.', NULL::integer, 6.0::numeric, 80, NULL::integer, NULL::integer, 3.2::numeric, 'ABB', 30, NULL::numeric, 100, 60),
  ('Bachelor in Electrical and Computer Engineering (English-taught)', NULL::numeric, 'QS Top 400 World (Engineering - Electrical). Taught entirely in English at FEUP. Apply via international portal by May 31. Mathematics and Physics background required. Strong analytical skills expected. Combined BSc/MSc integrated program available.', NULL::integer, 6.0::numeric, 80, NULL::integer, NULL::integer, 3.0::numeric, 'ABB', 30, NULL::numeric, 100, 60),
  ('Licenciatura em Medicina (Medicine) - Portuguese-medium', NULL::numeric, 'QS Top 200 World (Medicine). Taught in Portuguese at FMUP (Faculty of Medicine). Portuguese B2 proficiency required for non-native speakers. Apply via national Concurso Nacional de Acesso or international portal. Strong Biology and Chemistry background essential. One of Portugal''s leading medical schools. 6-year program.', NULL::integer, NULL::numeric, NULL::integer, NULL::integer, NULL::integer, 3.8::numeric, 'A*AA', 36, NULL::numeric, NULL::integer, NULL::integer),
  ('Bachelor in Economics (Licenciatura em Economia)', NULL::numeric, 'QS Top 300 World (Economics & Econometrics). Primarily taught in Portuguese at FEP (Faculty of Economics). Some courses available in English. Apply via international portal by May 31. Mathematics background important. FEP is one of Portugal''s top economics faculties. English-track pathway available for international students in select modules.', NULL::integer, 6.0::numeric, 79, NULL::integer, NULL::integer, 3.0::numeric, 'ABB', 29, NULL::numeric, 100, 58),
  ('Bachelor in Business Administration (Gestao)', NULL::numeric, 'QS Top 400 World (Business & Management Studies). Offered at FEP (Faculty of Economics). Primarily in Portuguese with English-medium modules available. Apply via international portal by May 31. Good numerical and analytical aptitude expected. Strong graduate employment outcomes. Exchange partnerships with 200+ European universities.', NULL::integer, 6.0::numeric, 79, NULL::integer, NULL::integer, 3.0::numeric, 'ABB', 28, NULL::numeric, 100, 58),
  ('Bachelor in Architecture (Licenciatura em Arquitectura)', NULL::numeric, 'QS Top 100 World (Architecture). Offered at FAUP (Faculty of Architecture), one of Europe''s most acclaimed architecture schools. Portfolio submission required (12-15 works showing creative/technical ability). Taught in Portuguese. Apply via national access or international portal by April 30. Design aptitude test may be required.', NULL::integer, 6.0::numeric, 79, NULL::integer, NULL::integer, 3.2::numeric, 'ABB', 30, NULL::numeric, NULL::integer, NULL::integer),
  ('Bachelor in Bioengineering (Bioengenharia)', NULL::numeric, 'QS Top 300 World (Biological Sciences). Joint degree between FEUP and ICBAS (Institute of Biomedical Sciences). Taught in Portuguese with English content in advanced modules. Strong Biology, Chemistry, and Mathematics background required. Apply via international portal by May 31. Interdisciplinary program at forefront of Portuguese biomedical research.', NULL::integer, 6.0::numeric, 79, NULL::integer, NULL::integer, 3.2::numeric, 'ABB', 30, NULL::numeric, 100, 58),
  ('Bachelor in Chemistry (Licenciatura em Quimica)', NULL::numeric, 'QS Top 400 World (Chemistry). Offered at Faculty of Sciences (FCUP). Taught in Portuguese. Apply via international portal by May 31. Strong Chemistry, Physics, and Mathematics background required. Access to excellent laboratory facilities. Articulation with Masters and PhD pathways.', NULL::integer, 6.0::numeric, 79, NULL::integer, NULL::integer, 3.0::numeric, 'ABB', 28, NULL::numeric, 100, 58),
  ('Bachelor in International Relations (Licenciatura em Relacoes Internacionais)', NULL::numeric, 'QS Top 400 World (Politics & International Studies). Offered at Faculty of Arts and Humanities (FLUP). Primarily in Portuguese. Apply via international portal by May 31. Strong background in humanities and social sciences. English reading proficiency useful. Some modules taught in English/French/Spanish. Active Model United Nations chapter.', NULL::integer, 6.0::numeric, 79, NULL::integer, NULL::integer, 3.0::numeric, 'ABB', 28, NULL::numeric, 100, 58)
) AS v(major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
WHERE u.name = 'University of Porto';
