INSERT INTO public.majors (university_id, major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
SELECT u.id, v.major_name, v.acceptance_rate, v.supplemental_requirements, v.subject_ranking, v.ielts_min, v.toefl_min, NULL::INTEGER, NULL::INTEGER, NULL::NUMERIC, NULL::TEXT, v.ib_min, v.atar_min, NULL::INTEGER, v.pte_min
FROM public.universities u
CROSS JOIN (VALUES
  ('Computer Science',         '75%', 'Prerequisites: Year 12 Mathematics Advanced or equivalent recommended; apply via UAC',                                                                                              NULL::INTEGER, 6.0::NUMERIC, 79, 26, 65.0::NUMERIC, 58),
  ('Engineering (Honours)',    '70%', 'Prerequisites: Year 12 Mathematics and Physics or Chemistry; 4-year honours-integrated program; apply via UAC',                                                                     NULL::INTEGER, 6.0::NUMERIC, 79, 26, 65.0::NUMERIC, 58),
  ('Business',                 '80%', 'Prerequisites: Year 12 Mathematics Standard 2 or equivalent; covers management, marketing, accounting, and finance; apply via UAC',                                                 NULL::INTEGER, 6.0::NUMERIC, 79, 24, 60.0::NUMERIC, 58),
  ('Nursing',                  '72%', 'Prerequisites: Year 12 English and Biology or Chemistry recommended; IELTS 7.0 with no band below 7.0 for AHPRA registration; clinical placements required; apply via UAC',        NULL::INTEGER, 7.0::NUMERIC, 94, 28, 70.0::NUMERIC, 65),
  ('Psychology',               '75%', 'Prerequisites: Year 12 English; fourth-year honours stream requires separate application; accredited by APS; apply via UAC',                                                       NULL::INTEGER, 6.5::NUMERIC, 79, 26, 65.0::NUMERIC, 58),
  ('Science',                  '80%', 'Prerequisites: Year 12 Mathematics recommended; broad program with majors in Biology, Chemistry, Mathematics, and Physics; apply via UAC',                                         NULL::INTEGER, 6.0::NUMERIC, 79, 24, 60.0::NUMERIC, 58),
  ('Law',                      '65%', 'Prerequisites: Year 12 English Advanced or equivalent; offered as combined degree or standalone; apply via UAC',                                                                   NULL::INTEGER, 7.0::NUMERIC, 94, 30, 75.0::NUMERIC, 65),
  ('Education',                '78%', 'Prerequisites: Year 12 English Band 4 minimum; LANTITE literacy and numeracy test required prior to graduation; apply via UAC',                                                    NULL::INTEGER, 7.0::NUMERIC, 94, 26, 65.0::NUMERIC, 65),
  ('Health Sciences',          '75%', 'Prerequisites: Year 12 English and one science subject recommended; broad health pathway covering public health, exercise science, and health promotion; apply via UAC',            NULL::INTEGER, 6.5::NUMERIC, 79, 26, 65.0::NUMERIC, 58),
  ('Arts and Social Sciences', '80%', 'Prerequisites: Year 12 English; broad interdisciplinary program covering humanities, social sciences, and communications; apply via UAC',                                           NULL::INTEGER, 6.0::NUMERIC, 79, 24, 60.0::NUMERIC, 58)
) AS v(major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, ib_min, atar_min, pte_min)
WHERE u.name = 'University of Wollongong';
