INSERT INTO public.majors (university_id, major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
SELECT u.id, v.major_name, v.acceptance_rate, v.supplemental_requirements, v.subject_ranking, v.ielts_min, v.toefl_min, v.sat_min, v.act_min, v.gpa_min, v.a_level_grades, v.ib_min, v.atar_min, v.duolingo_min, v.pte_min
FROM public.universities u
CROSS JOIN (VALUES
  ('Bachelor of Design (Communication Design)',             '65%', 'Standard application via VTAC; portfolio not required for entry; AUD $35,520/yr international tuition; ATAR 70',                              NULL::INTEGER, 6.5, 79, NULL::INTEGER, NULL::INTEGER, NULL::NUMERIC, 'BCC', 26, 70.0, 105, 58),
  ('Bachelor of Engineering (Honours) (Civil Engineering)', '60%', 'Standard application via VTAC; assumed knowledge of Mathematics Methods and Physics; AUD $48,504/yr international tuition; ATAR 75',           NULL::INTEGER, 6.5, 79, NULL::INTEGER, NULL::INTEGER, NULL::NUMERIC, 'BBC', 28, 75.0, 105, 58),
  ('Bachelor of Business (Management)',                     '75%', 'Standard application via VTAC; no prerequisite subjects; AUD $33,600/yr international tuition; ATAR 65',                                       NULL::INTEGER, 6.5, 79, NULL::INTEGER, NULL::INTEGER, NULL::NUMERIC, 'BCC', 24, 65.0, 105, 58),
  ('Bachelor of Information Technology',                    '70%', 'Standard application via VTAC; assumed knowledge of Mathematics; AUD $40,320/yr international tuition; ATAR 70',                               NULL::INTEGER, 6.5, 79, NULL::INTEGER, NULL::INTEGER, NULL::NUMERIC, 'BCC', 26, 70.0, 105, 58),
  ('Bachelor of Architecture (Honours)',                    '55%', 'Standard application via VTAC; no portfolio required for undergraduate entry; 5-year honours program; AUD $37,440/yr international tuition; ATAR 80', NULL::INTEGER, 6.5, 79, NULL::INTEGER, NULL::INTEGER, NULL::NUMERIC, 'BBB', 28, 80.0, 110, 58),
  ('Bachelor of Engineering (Honours) (Mechanical Engineering)', '60%', 'Standard application via VTAC; assumed knowledge of Mathematics Methods and Physics; AUD $48,504/yr international tuition; ATAR 75',      NULL::INTEGER, 6.5, 79, NULL::INTEGER, NULL::INTEGER, NULL::NUMERIC, 'BBC', 28, 75.0, 105, 58),
  ('Bachelor of Fashion (Design)',                          '60%', 'Standard application via VTAC; portfolio submission required post-offer; AUD $35,520/yr international tuition; ATAR 70',                        NULL::INTEGER, 6.5, 79, NULL::INTEGER, NULL::INTEGER, NULL::NUMERIC, 'BCC', 26, 70.0, 105, 58),
  ('Bachelor of Business (Accounting)',                     '70%', 'Standard application via VTAC; assumed knowledge of Mathematics; CPA/CA pathways available; AUD $33,600/yr international tuition; ATAR 68',    NULL::INTEGER, 6.5, 79, NULL::INTEGER, NULL::INTEGER, NULL::NUMERIC, 'BCC', 25, 68.0, 105, 58),
  ('Bachelor of Computer Science',                          '65%', 'Standard application via VTAC; assumed knowledge of Mathematics Methods; AUD $40,320/yr international tuition; ATAR 72',                       NULL::INTEGER, 6.5, 79, NULL::INTEGER, NULL::INTEGER, NULL::NUMERIC, 'BCC', 26, 72.0, 105, 58),
  ('Bachelor of Applied Science (Psychology)',              '72%', 'Standard application via VTAC; no specific prerequisites; APAC-accredited; AUD $34,560/yr international tuition; ATAR 68',                     NULL::INTEGER, 6.5, 79, NULL::INTEGER, NULL::INTEGER, NULL::NUMERIC, 'BCC', 25, 68.0, 105, 58)
) AS v(major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
WHERE u.name = 'RMIT University';
