-- Part 1: University-level data for Georg-August-Universität Göttingen
UPDATE public.universities SET
  website_url = 'https://www.uni-goettingen.de/en/',
  tuition_usd = 1007,
  overall_acceptance_rate = '15%',
  test_policy = 'Not applicable',
  deadline_calendar = 'Winter semester (Oct start): July 15; Summer semester (Apr start): January 15. International students apply via uni-assist portal (www.uni-assist.de). Restricted programs (Medicine, Dentistry, Pharmacy, Psychology) apply via hochschulstart.de. Early application strongly recommended for visa processing time.',
  financial_aid = 'No tuition fees; only semester contribution fee of €466.40 (Summer 2026) / €436.36 (Winter 2025/26) covering student services, public transport pass (Semesterticket), and administration. Deutschlandstipendium (€300/month merit-based, open to all nationalities); DAAD scholarships (various programs for international students); Lower Saxony Scholarship (€500–€1,000 for academic achievement); Göttingen International Scholarship; emergency financial aid via Studentenwerk. Blocked account of ~€11,904/year required for German student visa.'
WHERE name = 'Georg-August-Universität Göttingen';

-- Part 2: Top 10 majors for Georg-August-Universität Göttingen
INSERT INTO public.majors (university_id, major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
SELECT u.id, v.major_name, v.acceptance_rate, v.supplemental_requirements, v.subject_ranking, v.ielts_min, v.toefl_min, v.sat_min, v.act_min, v.gpa_min, v.a_level_grades, v.ib_min, v.atar_min, v.duolingo_min, v.pte_min
FROM public.universities u
CROSS JOIN (VALUES
  ('Applied Computer Science (B.Sc.)', '25%', 'Admission-free (no NC) in most semesters; program taught primarily in English; strong mathematics background required; apply via uni-assist portal by July 15 for winter semester; German language skills helpful but not mandatory for English-taught modules', 51, 6.5, 95, NULL::int, NULL::int, 2.5::numeric, 'AAB', 34, NULL::numeric, 110, 62),
  ('Physics (B.Sc.)', '30%', 'Admission-free (no NC); German C1-C2 required (DSH-2 or TestDaF 4x4) for most modules; strong mathematics and physics background essential; Göttingen has a legendary physics tradition (home of Max Born, Werner Heisenberg, David Hilbert); laboratory work from first semester', 1, NULL::numeric, NULL::int, NULL::int, NULL::int, 2.0::numeric, 'AAB', 34, NULL::numeric, NULL::int, NULL::int),
  ('Mathematics (B.Sc.)', '30%', 'Admission-free (no NC); German C1-C2 required (DSH-2 or TestDaF 4x4); very strong mathematics background essential; Göttingen mathematics is historically world-renowned (Gauss, Riemann, Hilbert); apply via uni-assist portal', 1, NULL, NULL, NULL, NULL, 2.0, 'AAB', 34, NULL, NULL, NULL),
  ('Economics (B.Sc.)', '20%', 'Locally restricted admission (NC) in some semesters; German C1-C2 required (DSH-2 or TestDaF 4x4); strong mathematics background required; program covers microeconomics, macroeconomics, and econometrics; apply via uni-assist by July 15', 51, NULL, NULL, NULL, NULL, 2.0, 'AAA', 35, NULL, NULL, NULL),
  ('Biology (B.Sc.)', '20%', 'Locally restricted admission (NC); German C1-C2 required (DSH-2 or TestDaF 4x4); strong natural sciences background required; laboratory and fieldwork components from first semester; research-oriented program; Göttingen is strong in ecology, evolutionary biology, and molecular biology', 35, NULL, NULL, NULL, NULL, 2.0, 'AAA', 35, NULL, NULL, NULL),
  ('Forest Sciences and Forest Ecology (B.Sc.)', '35%', 'Admission-free (no NC); German C1-C2 required (DSH-2 or TestDaF 4x4); Göttingen has Germany''s oldest and most prestigious forestry faculty (founded 1868); fieldwork in Harz and Solling forests included; strong natural sciences background recommended', 1, NULL, NULL, NULL, NULL, 2.5, 'ABB', 33, NULL, NULL, NULL),
  ('Agricultural Sciences (B.Sc.)', '30%', 'Admission-free (no NC); German C1-C2 required (DSH-2 or TestDaF 4x4); Göttingen''s faculty of agricultural sciences is internationally top-ranked; covers crop science, animal science, agribusiness; fieldwork components included; apply via uni-assist portal', 1, NULL, NULL, NULL, NULL, 2.5, 'ABB', 33, NULL, NULL, NULL),
  ('Geosciences (B.Sc.)', '30%', 'Admission-free (no NC); German C1-C2 required (DSH-2 or TestDaF 4x4); strong natural sciences background (geography, chemistry, physics) recommended; fieldwork included; covers geology, mineralogy, and environmental geosciences; apply via uni-assist by July 15', 51, NULL, NULL, NULL, NULL, 2.5, 'ABB', 33, NULL, NULL, NULL),
  ('Chemistry (B.Sc.)', '25%', 'Admission-free (no NC); German C1-C2 required (DSH-2 or TestDaF 4x4); strong chemistry and mathematics background required; laboratory work from first semester; Göttingen has a distinguished chemistry tradition; apply via uni-assist portal', 51, NULL, NULL, NULL, NULL, 2.0, 'AAB', 34, NULL, NULL, NULL),
  ('Psychology (B.Sc.)', '8%', 'Highly competitive locally restricted admission (NC); German C1-C2 required (DSH-2 or TestDaF 4x4); apply via uni-assist portal; strong interest in empirical and quantitative methods required; program covers clinical, cognitive, and social psychology; one of Göttingen''s most competitive programs', 51, NULL, NULL, NULL, NULL, 1.5, 'A*AA', 37, NULL, NULL, NULL)
) AS v(major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
WHERE u.name = 'Georg-August-Universität Göttingen';
