-- Part 1: University-level data for University of Lisbon (ULisboa)
-- Source: ulisboa.pt official pages, 2025/2026 data
-- EUR to USD conversion rate ~1.10 used; non-EU international student tuition €7,000 = ~$7,700 USD
UPDATE public.universities SET
  website_url = 'https://www.ulisboa.pt',
  tuition_usd = 7700,
  overall_acceptance_rate = '50%',
  test_policy = 'Not applicable',
  deadline_calendar = 'Applications for international students (Special Admission Competition, CEI): 1st round January–February; 2nd round April–May for the following academic year. Application fee €60. Selection based on secondary school final grades in required subjects. Portuguese language B1 level (CEFR) required for most programmes; English-taught programmes require B2 English. Applications submitted online via each Faculty portal.',
  financial_aid = 'ULisboa Social Action Scholarships (means-tested, covering tuition and living costs for eligible students); Erasmus+ mobility grants for exchange students; FCT (Foundation for Science and Technology) PhD scholarships; ULisboa Merit Scholarships for high-achieving students; various faculty-level grants. International students may apply for Portuguese government scholarship schemes. Tuition fee for international students may be reduced to the domestic rate (€697/year) in cases of demonstrated financial need.'
WHERE name = 'University of Lisbon';

-- Part 2: Top 10 undergraduate majors for University of Lisbon
-- Most programmes taught in Portuguese; international students must demonstrate B1 Portuguese.
-- No SAT, ACT, or ATAR used in Portuguese admissions. IELTS/TOEFL required for English-instruction programmes.
-- Acceptance rates reflect competitive ratio at ULisboa faculties (overall ~50%, varies by programme).
-- Tuition for non-EU international students: €7,000/year (~$7,700 USD) for most programmes.
INSERT INTO public.majors (university_id, major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
SELECT u.id, v.major_name, v.acceptance_rate, v.supplemental_requirements, v.subject_ranking, v.ielts_min, v.toefl_min, v.sat_min, v.act_min, v.gpa_min, v.a_level_grades, v.ib_min, v.atar_min, v.duolingo_min, v.pte_min
FROM public.universities u
CROSS JOIN (VALUES
  ('Licenciatura em Direito (Law)', '45%', 'Instruction in Portuguese; B1 Portuguese required. Secondary school diploma with passing grades in humanities or social sciences subjects. Selection based on secondary education final average grade. No entrance exam. Application via CEI competition for international students.', NULL::integer, 6.0::numeric, 80, NULL::integer, NULL::integer, NULL::numeric, 'BBB', 30, NULL::numeric, 95, 58),
  ('Licenciatura em Economia (Economics)', '50%', 'Instruction in Portuguese; B1 Portuguese required. Strong secondary school grades in Mathematics required. Selection based on secondary education final average. Application via ISEG (Lisbon School of Economics and Management). Mathematics-focused applicants preferred.', NULL::integer, 6.0::numeric, 80, NULL::integer, NULL::integer, NULL::numeric, 'BBB', 30, NULL::numeric, 95, 58),
  ('Licenciatura em Engenharia Informatica e de Computadores (Computer Science and Engineering)', '40%', 'Instruction in Portuguese; B1 Portuguese required. Strong secondary school grades in Mathematics and Physics required. Selection based on secondary education final average in Mathematics and Physics. Application via Tecnico Lisboa (IST). Competitive programme with high demand.', NULL::integer, 6.0::numeric, 80, NULL::integer, NULL::integer, NULL::numeric, 'BBB', 32, NULL::numeric, 95, 58),
  ('Licenciatura em Gestao (Management)', '55%', 'Instruction in Portuguese; B1 Portuguese required. Secondary school diploma required; Mathematics grades valued. Selection based on secondary education final average. Application via ISEG. Personal motivation and academic record considered.', NULL::integer, 6.0::numeric, 80, NULL::integer, NULL::integer, NULL::numeric, 'BBB', 30, NULL::numeric, 95, 58),
  ('Licenciatura em Medicina (Medicine)', '15%', 'Instruction in Portuguese; B1 Portuguese required. Secondary school diploma with strong Biology and Chemistry grades required. National entrance exam scores considered (or equivalent). Selection highly competitive based on secondary final average. Application via Faculty of Medicine (FMUL). Very limited international vacancies.', NULL::integer, 6.5::numeric, 90, NULL::integer, NULL::integer, NULL::numeric, 'AAB', 34, NULL::numeric, 100, 65),
  ('Licenciatura em Engenharia Eletrotecnica e de Computadores (Electrical and Computer Engineering)', '42%', 'Instruction in Portuguese; B1 Portuguese required. Strong secondary school grades in Mathematics and Physics required. Selection based on secondary education final average. Application via Tecnico Lisboa (IST). Internationally recognized engineering programme.', NULL::integer, 6.0::numeric, 80, NULL::integer, NULL::integer, NULL::numeric, 'BBB', 31, NULL::numeric, 95, 58),
  ('Licenciatura em Psicologia (Psychology)', '48%', 'Instruction in Portuguese; B1 Portuguese required. Secondary school diploma required; Biology or Social Sciences background valued. Selection based on secondary education final average. Application via Faculty of Psychology (FPUL). Limited international vacancies per intake.', NULL::integer, 6.0::numeric, 80, NULL::integer, NULL::integer, NULL::numeric, 'BBB', 30, NULL::numeric, 95, 58),
  ('Licenciatura em Biologia (Biology)', '50%', 'Instruction in Portuguese; B1 Portuguese required. Secondary school diploma with Biology and Chemistry or Physics and Mathematics. Selection based on secondary education final average in sciences. Application via Faculty of Sciences (Ciencias ULisboa). Research-oriented programme.', NULL::integer, 6.0::numeric, 80, NULL::integer, NULL::integer, NULL::numeric, 'BBB', 30, NULL::numeric, 95, 58),
  ('Licenciatura em Sociologia (Sociology)', '60%', 'Instruction in Portuguese; B1 Portuguese required. Secondary school diploma; humanities or social sciences background preferred. Selection based on secondary education final average. Application via ISCSP (School of Social and Political Sciences). Evening/after-work option available.', NULL::integer, 6.0::numeric, 80, NULL::integer, NULL::integer, NULL::numeric, 'BCC', 29, NULL::numeric, 95, 58),
  ('Licenciatura em Estudos Europeus (European Studies)', '55%', 'Instruction in Portuguese with significant English-language component; B1 Portuguese and B2 English required. Humanities or social sciences secondary school background preferred. Selection based on secondary education final average. Application via Faculty of Arts and Humanities (FLUL). International and interdisciplinary focus.', NULL::integer, 6.0::numeric, 80, NULL::integer, NULL::integer, NULL::numeric, 'BCC', 30, NULL::numeric, 95, 58)
) AS v(major_name, acceptance_rate, supplemental_requirements, subject_ranking, ielts_min, toefl_min, sat_min, act_min, gpa_min, a_level_grades, ib_min, atar_min, duolingo_min, pte_min)
WHERE u.name = 'University of Lisbon';
